force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <label>State Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDEN_GetStateMasterTest.cls
/**
* @File Name : MDEN_GetStateMasterTest.cls
* @Description : Test Class for MDEN_GetStateMaster.cls
* @Author : Abhishek
* @Last Modified By : Abhishek
* @Last Modified On : April 10, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 10, 2025 |  Abhishek | Initial Version
**/
@isTest
public class MDEN_GetStateMasterTest {
    
    @isTest
    static void testGetStateSuccess() {
        // creating Test Data
        Country__c country = new Country__c();
        country.Country_Name__c = 'India' ;
        insert country;
        
        List<State__c> stateList = new List<State__c>();
        State__c state1 = new State__c();
        state1.State_Name__c = 'Delhi';
        state1.Country__c = country.Id;
        stateList.add(state1);
        
        State__c state2 = new State__c();
        state2.State_Name__c = 'Maharashtra';
        state2.Country__c = country.Id;        
        stateList.add(state2);
        
        insert stateList;
        // creating RestRequest
        MDEN_GetStateMaster.MDEN_GetRequestWrapper reqWrapper = new MDEN_GetStateMaster.MDEN_GetRequestWrapper();
        reqWrapper.country_id = 'India';
        String jsonReq = JSON.serialize(reqWrapper);
        
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/get_state/';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueOf(jsonReq);
        RestContext.request = req;
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        MDEN_GetStateMaster.MDEN_GetResponseWrapper response = MDEN_GetStateMaster.getState();
        Test.stopTest();
        
        System.assertEquals('true', response.status);        
        System.assertEquals('data found.', response.message);        
    }
    
    @isTest
    static void testGetStateNoMatch() {
        
        MDEN_GetStateMaster.MDEN_GetRequestWrapper reqWrapper = new MDEN_GetStateMaster.MDEN_GetRequestWrapper();
        reqWrapper.country_id = 'NonExistingCountry';
        String jsonReq = JSON.serialize(reqWrapper);
        
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/get_state/';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueOf(jsonReq);
        RestContext.request = req;
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        MDEN_GetStateMaster.MDEN_GetResponseWrapper response = MDEN_GetStateMaster.getState();
        Test.stopTest();
        
        System.assertEquals('false', response.status);
        System.assertEquals('data not found.', response.message);
    }
}