force-app/main/default/objects/Cancellation_And_Refund__mdt/Cancellation_And_Refund__mdt.object-meta.xml
<CustomObject>
    <label>Cancellation And Refund</label>
    <pluralLabel>Cancellation And Refunds</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cancellation_And_Refund__mdt/fields/Charges__c.field-meta.xml
<CustomField>
    <fullName>Charges__c</fullName>
    <label>Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cancellation_And_Refund__mdt/fields/Greater_Than__c.field-meta.xml
<CustomField>
    <fullName>Greater_Than__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if time frame is greater than the selected time frame</description>
    <label>Greater Than</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cancellation_And_Refund__mdt/fields/Less_Than__c.field-meta.xml
<CustomField>
    <fullName>Less_Than__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if the time frame is less than the selected time frame.</description>
    <label>Less Than</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cancellation_And_Refund__mdt/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
                <default>true</default>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Add Ons</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cancellation_And_Refund__mdt/fields/Refund_Policy__c.field-meta.xml
<CustomField>
    <fullName>Refund_Policy__c</fullName>
    <label>Refund Policy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cancellation_And_Refund__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cancellation_And_Refund__mdt/fields/Time_Frame__c.field-meta.xml
<CustomField>
    <fullName>Time_Frame__c</fullName>
    <label>Time Frame</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
                <default>true</default>
                <label>12</label>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>12-24</fullName>
            </value>
            <value>
                <fullName>24-48</fullName>
            </value>
            <value>
                <fullName>Unlimited</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Detail</label>
    <nameField>
        <label>Passengers Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger_Details__c/fields/Individual_Booking_Details__c.field-meta.xml
<CustomField>
    <fullName>Individual_Booking_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Booking Details</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Passenger Details</relationshipLabel>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Type__c</fullName>
    <label>Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Infant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancellationPolicyService.cls
public class CancellationPolicyService {
    public static String refundPolicy='';
    public static String addAnd =' & ';

    public static Decimal getGeneralCancellationPolicyAmount(DateTime serviceDateTime, DateTime cancellationDateTime, Decimal bookingAmount) {
        if (refundPolicy != '') {
            addAnd = ' & ';
        } else {
            addAnd = '';
        }

        Long hoursDifference = serviceDateTime.getTime() - cancellationDateTime.getTime();
        hoursDifference = hoursDifference / (1000 * 60 * 60);  // Convert milliseconds to hours
        Cancellation_And_Refund__mdt generalMetadataRecord = Cancellation_And_Refund__mdt.getInstance('Cancellation_General_Bank_Charges');
        if (generalMetadataRecord != null &&
            generalMetadataRecord.Less_Than__c && 
            hoursDifference < Long.valueOf(generalMetadataRecord.Time_Frame__c)) {
                if (generalMetadataRecord.Charges_in_Percentage__c) {
                    refundPolicy = refundPolicy + addAnd + generalMetadataRecord.Refund_Policy__c;
                    return bookingAmount = bookingAmount - (bookingAmount * (generalMetadataRecord.Charges__c / 100));
                } else {
                    refundPolicy = refundPolicy + addAnd + generalMetadataRecord.Refund_Policy__c;
                    return bookingAmount = bookingAmount - generalMetadataRecord.Charges__c;
                } 
        } else if (generalMetadataRecord != null &&
            generalMetadataRecord.Greater_Than__c && 
            Long.valueOf(generalMetadataRecord.Time_Frame__c) < hoursDifference) {
            if (generalMetadataRecord.Charges_in_Percentage__c) {
                refundPolicy = refundPolicy + addAnd + generalMetadataRecord.Refund_Policy__c;
                return bookingAmount = bookingAmount - (bookingAmount * (generalMetadataRecord.Charges__c / 100));
            } else {
                refundPolicy = refundPolicy + addAnd + generalMetadataRecord.Refund_Policy__c;
                return bookingAmount = bookingAmount - generalMetadataRecord.Charges__c;
            } 
        }
        return bookingAmount;
    }

    public static Decimal getCancellationPolicyAmount(DateTime serviceDateTime, DateTime cancellationDateTime, Decimal bookingAmount, String packageName) {
        // Calculate the difference in hours between the service and cancellation times
        Long hoursDifference = serviceDateTime.getTime() - cancellationDateTime.getTime();
        hoursDifference = hoursDifference / (1000 * 60 * 60);  // Convert milliseconds to hours
        system.debug('hoursDifference ->> '+hoursDifference);
        // Query the cancellation policies
        List<Cancellation_And_Refund__mdt> policies = [SELECT MasterLabel, Time_Frame__c,
                                                   Charges_in_Percentage__c, Charges__c,
                                                   Greater_Than__c, Less_Than__c, Package__c,Refund_Policy__c
                                                   FROM Cancellation_And_Refund__mdt 
                                                   WHERE IsActive__c = true
                                                   AND (Package__c =:packageName)
                                                   ORDER BY Sort_Order__c];

        // Iterate through policies to find the applicable one
        for (Cancellation_And_Refund__mdt policy : policies) {
                if (policy.Less_Than__c &&  hoursDifference < Long.valueOf(policy.Time_Frame__c)) {
                    if (policy.Charges_in_Percentage__c) {
                        system.debug('policy ->> '+policy.Refund_Policy__c);
                        refundPolicy = policy.Refund_Policy__c;
                        return bookingAmount - (bookingAmount * (policy.Charges__c / 100));
                    } else {
                        system.debug('policy ->> '+policy.Refund_Policy__c);
                        refundPolicy = policy.Refund_Policy__c;
                        return bookingAmount - policy.Charges__c;
                    } 
                } 
                else if (policy.Greater_Than__c && Long.valueOf(policy.Time_Frame__c) < hoursDifference) {
                    if (policy.Charges_in_Percentage__c) {
                        system.debug('policy ->> '+policy.Refund_Policy__c);
                        refundPolicy = policy.Refund_Policy__c;
                        return bookingAmount - (bookingAmount * (policy.Charges__c / 100));
                    } else {
                        system.debug('policy ->> '+policy.Refund_Policy__c);
                        refundPolicy = policy.Refund_Policy__c;
                        return bookingAmount - policy.Charges__c;
                    } 
                }
                else if (policy.Time_Frame__c.contains('-')) {
                    List<String> rangeValues = policy.Time_Frame__c.split('-');
                    system.debug('rangeValues '+rangeValues);
                    Integer lowerValue = Integer.valueOf(rangeValues[0]); // First value (24)
                    Integer upperValue = Integer.valueOf(rangeValues[1]); // Second value (48)
                    system.debug('lowerValue '+lowerValue);
                    system.debug('upperValue '+upperValue);
                    if (hoursDifference > lowerValue && hoursDifference < upperValue) {
                        if (policy.Charges_in_Percentage__c) {
                            system.debug('policy ->> '+policy.Refund_Policy__c);
                            refundPolicy = policy.Refund_Policy__c;
                            return bookingAmount - (bookingAmount * (policy.Charges__c / 100));
                        } else {
                            system.debug('policy ->> '+policy.Refund_Policy__c);
                            refundPolicy = policy.Refund_Policy__c;
                            return bookingAmount - policy.Charges__c;
                        } 
                    }
                }
                else if (policy.Time_Frame__c == 'Unlimited') {
                    if (policy.Charges_in_Percentage__c) {
                        system.debug('policy ->> '+policy.Refund_Policy__c);
                        refundPolicy = policy.Refund_Policy__c;
                        bookingAmount = bookingAmount - (bookingAmount * (policy.Charges__c / 100));
                    } else {
                        system.debug('policy ->> '+policy.Refund_Policy__c);
                        refundPolicy = policy.Refund_Policy__c;
                        bookingAmount = bookingAmount - policy.Charges__c;
                    } 
                }
            
        }
        // Default to no charge if no policy matches
        system.debug('policy ->> no policy ');
        return bookingAmount;
    }

    @AuraEnabled
    public static cancellationDetailsWrapper showCancellationCharges(String cancelType,
    List<Map<String, Object>> selectedOrders,
        Decimal bookingAmount,
        String packageName,
        String opportunityId,
        Integer numberOfPax,
        Boolean submit) {
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        List<OpportunityLineItem> oliNewList = new List<OpportunityLineItem>();
        cancellationDetailsWrapper wrp = new cancellationDetailsWrapper();
        DateTime serviceDateTime;
        String dateText;
        String timeText;
        String combinedDateTimeStr;
        // Query OpportunityLineItems based on OpportunityId
        Opportunity opp = [
            SELECT STA_Time__c,STD_Time__c,Date_of_Arrival__c,Date_of_Departure__c,Amount,
            (SELECT Id,Product2.Family,UnitPrice,PricebookEntryId FROM opportunitylineitems WHERE Status__c = 'Active') 
            FROM Opportunity
            WHERE Id=:opportunityId
            LIMIT 1
        ];
        
        if (opp.STA_Time__c != null) {
            dateText=opp.Date_of_Arrival__c;
            timeText=opp.STA_Time__c;
            // Ensure timeText includes seconds
            if (timeText.length() == 5) {  // "HH:mm" format
                timeText += ':00';  // Append ":00" for seconds
            }
            combinedDateTimeStr=dateText + ' ' + timeText;
            serviceDateTime = DateTime.valueOf(combinedDateTimeStr);
        } else if (opp.STD_Time__c != null) {
            dateText=opp.Date_of_Departure__c;
            timeText=opp.STD_Time__c;
            combinedDateTimeStr=dateText + ' ' + timeText;
            serviceDateTime = DateTime.valueOf(combinedDateTimeStr);
        }
        if (cancelType =='fullCancel') {    
            Cancellation_And_Refund__mdt metadataRecord = [SELECT Package__c FROM Cancellation_And_Refund__mdt LIMIT 1];           
            numberOfPax = opp.opportunitylineitems.size();    
            bookingAmount = 0;     
            for (opportunitylineitem oli: opp.opportunitylineitems) {
                packageName = metadataRecord.Package__c.contains(oli.Product2.Family) ? oli.Product2.Family: '';
                bookingAmount += oli.UnitPrice;   
                if(submit) {
                    oli.Status__c = 'Fully Cancelled';
                    oliList.add(oli);
                OpportunityLineItem oliNew = new OpportunityLineItem();
                decimal refundAmountPerOli = getCancellationPolicyAmount(serviceDateTime, DateTime.now(), oli.UnitPrice, packageName);
                oliNew.Status__c = 'Cancellation';
                oliNew.OpportunityId = opportunityId;
                oliNew.UnitPrice = refundAmountPerOli;
                oliNew.Refund_Amount__c = refundAmountPerOli;
                oliNew.Quantity = 1;
                oliNew.Amount_Deducted__c= oli.UnitPrice-refundAmountPerOli;
                oliNew.PricebookEntryId=oli.PricebookEntryId;
                oliNewList.add(oliNew); 
                }          
            }
            update oliList;            
            insert oliNewList;
        }
        decimal afterCancellationRefundAmount = getCancellationPolicyAmount(serviceDateTime, DateTime.now(), bookingAmount, packageName);
        decimal afterGeneralCancellationRefund =  getGeneralCancellationPolicyAmount(serviceDateTime, DateTime.now(), afterCancellationRefundAmount);
        wrp.bookingAmount = bookingAmount;
        wrp.refundAmount = afterGeneralCancellationRefund;
        wrp.deductedAmount = bookingAmount - afterGeneralCancellationRefund;
        wrp.refundMethod = 'Original Payment Mode';
        wrp.numberOfPaxCancelled = numberOfPax;
        wrp.refundPolicyApplicable = refundPolicy;

        
        if (submit && cancelType !='fullCancel') {            
            for (Map<String, Object> row : selectedOrders) {                
                String pckName = (String) row.get('packageName');
                Decimal perUnitPrice = (Decimal) row.get('unitPrice');
                if((Id) row.get('oliId') !=null) {
                    OpportunityLineItem oli = new OpportunityLineItem(); 
                    oli.Id = (Id) row.get('oliId');
                    oli.Status__c = 'Partially Cancelled';
                    oliList.add(oli);
                }                
                OpportunityLineItem oliNew = new OpportunityLineItem();
                decimal refundAmountPerOli = getCancellationPolicyAmount(serviceDateTime, DateTime.now(), perUnitPrice, pckName);
                oliNew.Status__c = 'Cancellation';
                oliNew.OpportunityId = opportunityId;
                oliNew.UnitPrice = refundAmountPerOli;
                oliNew.Refund_Amount__c = refundAmountPerOli;
                oliNew.Quantity = 1;
                oliNew.Amount_Deducted__c= perUnitPrice -  refundAmountPerOli;
                oliNew.PricebookEntryId=(Id) row.get('pbenteryId');
                oliNewList.add(oliNew);                
            }
            update oliList;            
            insert oliNewList;
        }
        if(numberOfPax == 0) {
            return null;
        }
        return wrp;
    }

    @AuraEnabled(cacheable=true)
    public static List<passengerDetailsWrapper> getBookingToCancel(String opportunityId) {
        List<passengerDetailsWrapper> pdList = new List<passengerDetailsWrapper>();

        // Query OpportunityLineItems based on OpportunityId
        List<Passenger_Details__c> passengerList = [
            SELECT Id,Name, Individual_Booking_Details__r.UnitPrice, Individual_Booking_Details__c,
            Passenger_Type__c, Individual_Booking_Details__r.Product2.Family, Individual_Booking_Details__r.PricebookEntryId,
            Individual_Booking_Details__r.Status__c
            FROM Passenger_Details__c
            WHERE Opportunity_ID__c=:opportunityId AND Individual_Booking_Details__r.Status__c = 'Active'
        ];

        // Populate wrapper class list
        for (Passenger_Details__c pd : passengerList) {
            if(pd.Individual_Booking_Details__r.Status__c == 'Active'){                
                pdList.add(new passengerDetailsWrapper(pd));
            }
        }
        return pdList;
    }

    // Wrapper class to hold passengerDetails fields
    public class passengerDetailsWrapper {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String oliId { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String packageName { get; set; }
        @AuraEnabled public Decimal unitPrice { get; set; }
        @AuraEnabled public Integer quantity { get; set; }
        @AuraEnabled public String type { get; set; }
        @AuraEnabled public String pbenteryId { get; set; }

        public passengerDetailsWrapper(Passenger_Details__c pd) {
            this.id = pd.Id;
            this.oliId = pd.Individual_Booking_Details__c;
            this.name = pd.Name;
            this.packageName = pd.Individual_Booking_Details__r.Product2.Family;
            this.unitPrice = pd.Individual_Booking_Details__r.UnitPrice;
            this.quantity = 1;
            this.type = pd.Passenger_Type__c;
            this.pbenteryId =pd.Individual_Booking_Details__r.PricebookEntryId;

        }
    }

    public class cancellationDetailsWrapper {
        @AuraEnabled public Decimal bookingAmount;
        @AuraEnabled public Decimal refundAmount;
        @AuraEnabled public Decimal deductedAmount;
        @AuraEnabled public String refundMethod;
        @AuraEnabled public Integer numberOfPaxCancelled;
        @AuraEnabled public String refundPolicyApplicable;
    }
}