force-app/main/default/objects/Order_Request__c/Order_Request__c.object-meta.xml
<CustomObject>
    <description>This object will handle requested change order</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Order Requests</relationshipLabel>
    <relationshipName>Order_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Change_Type__c.field-meta.xml
<CustomField>
    <fullName>Change_Type__c</fullName>
    <label>Change Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Refund Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Order_Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Request_Number__c</fullName>
    <label>Order Request Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Total_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable_Amount__c</fullName>
    <label>Total Payable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/Payment_transaction__c.object-meta.xml
<CustomObject>
    <label>Payment transaction</label>
    <nameField>
        <label>Payment transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>payment transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_transaction__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>payment transactions</relationshipLabel>
    <relationshipName>payment_transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Id__c</fullName>
    <label>Invoice Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/Merchant_Reference_No__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Reference_No__c</fullName>
    <label>Merchant Reference No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/Order_Request__c.field-meta.xml
<CustomField>
    <fullName>Order_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Request</label>
    <referenceTo>Order_Request__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <label>QR Code</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/Tiny_URL__c.field-meta.xml
<CustomField>
    <fullName>Tiny_URL__c</fullName>
    <label>Tiny URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MDEN_PaymentLinkGenerator.cls
global with sharing class MDEN_PaymentLinkGenerator {
	 @Future(callout=true)
    global static  void sendRequest(String OppId) {
        Order_Request__c pendingRequest = OrderRequestController.getPendingRequest(OppId);
        List<Opportunity> oppList = [SELECT Id, Amount,Account.isPersonAccount, StageName,Name,Account.Name, Account.phone  FROM Opportunity where id =: OppId LIMIT 1];        
        if(oppList[0].Account.isPersonAccount)
        {
            Map<String, Object> invoiceData = new Map<String, Object>();        
            invoiceData.put('customer_name', oppList[0].Account.Name);
            invoiceData.put('bill_delivery_type', 'SMS');
            invoiceData.put('customer_mobile_no', '9999999999');
            //invoiceData.put('invoice_description', 'Test');
            invoiceData.put('currency', 'INR');
            invoiceData.put('valid_for', 3);
            invoiceData.put('valid_type', 'days');
            invoiceData.put('amount', pendingRequest !=null ? pendingRequest.Total_Payable_Amount__c : 1);
            invoiceData.put('merchant_reference_no', pendingRequest !=null ? pendingRequest.Order_Request_Number__c : oppList[0].Name);
            //invoiceData.put('merchant_reference_no1', 2);
            //invoiceData.put('merchant_reference_no2', 3);
            //invoiceData.put('merchant_reference_no3', 4);
            //invoiceData.put('merchant_reference_no4', 5);
            //invoiceData.put('terms_and_conditions', 'terms and condition');
            invoiceData.put('sms_content', 'Pls pay your LegalEntity_Name bill # Invoice_ID for Invoice_Currency Invoice_Amount online at  Pay_Link.');
            
            // Call the method
            String result = CCAvenueInvoiceService.createInvoice(invoiceData); 
            System.debug('Invoice API Response: ' + result);
            InvoiceResponseWrapper requestMap = InvoiceResponseWrapper.parse(result);
            if(requestMap != null ){
                Payment_transaction__c ptRec = new Payment_transaction__c();
                ptRec.QR_Code__c = requestMap.Generate_Invoice_Result.qr_code;   
                ptRec.Merchant_Reference_No__c = requestMap.Generate_Invoice_Result.merchant_reference_no ; 
                ptRec.Invoice_Id__c = requestMap.Generate_Invoice_Result.invoice_id ;  
                ptRec.Error_Description__c = requestMap.Generate_Invoice_Result.error_desc; 
                ptRec.Error_Code__c = requestMap.Generate_Invoice_Result.error_code ; 
                ptRec.Tiny_URL__c = requestMap.Generate_Invoice_Result.tiny_url; 
                ptRec.Invoice_Status__c = requestMap.Generate_Invoice_Result.invoice_status; 
                ptRec.Booking__c= OppId;
                ptRec.Order_Request__c = pendingRequest !=null ? pendingRequest.Id : null;
                if(ptRec != null){
                    insert ptRec;
                    String requestType = pendingRequest !=null ? pendingRequest.Change_Type__c : '';
                    BookingEmailHandler.sendEmailWithAttachment(OppId, requestType, ptRec.Tiny_URL__c);
                }
            }     
        }
        else
        {
           // oppList[0].StageName = 'Quotation Sent';
           // update oppList;
        }
    } 
}