force-app/main/default/objects/Order_Request__c/Order_Request__c.object-meta.xml
<CustomObject>
    <description>This object will handle requested change order</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Order Requests</relationshipLabel>
    <relationshipName>Order_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Change_Type__c.field-meta.xml
<CustomField>
    <fullName>Change_Type__c</fullName>
    <label>Change Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Refund Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Refund Initiated</fullName>
            </value>
            <value>
                <fullName>Refund Approved</fullName>
            </value>
            <value>
                <fullName>Refund Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RefundRequestController.cls
public class RefundRequestController {
    @AuraEnabled
    public static void createRefundRequest(String oppId){
        System.debug('createRefundRequest --oppId-->'+oppId);
        Decimal totalInvoiceAmt = 0;
        List<OpportunityLineItem> lineItemsToUpdateLst = new List<OpportunityLineItem>();
        List<OpportunityLineItem> cancelledList = [SELECT Id, OpportunityId, Status__c, Invoice_Amount__c, is_Refund_Initiated__c FROM OpportunityLineItem 
                                                   WHERE OpportunityId  =: oppId AND Status__c LIKE '%Cancelled%' AND is_Refund_Initiated__c = false];
        System.debug('cancelledList.size()-->'+cancelledList.size());
        for(OpportunityLineItem item : cancelledList){
            totalInvoiceAmt += item.Invoice_Amount__c;
        }
        if(totalInvoiceAmt > 0){
            Order_Request__c ordReq = new Order_Request__c();
            ordReq.Status__c = 'Refund Initiated';
            ordReq.Change_Type__c = 'Refund Request';
            ordReq.Booking__c = oppId;
            ordReq.Invoice_Amount__c = totalInvoiceAmt;
            insert ordReq;
            
            // Submit for Approval
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setObjectId(ordReq.Id);
            req.setSkipEntryCriteria(false); // Let the system evaluate your entry criteria
            Approval.ProcessResult result = Approval.process(req);
            System.debug('Approval Submitted: ' + result.isSuccess());
            
            for(OpportunityLineItem item : cancelledList){
                item.is_Refund_Initiated__c = true;
                lineItemsToUpdateLst.add(item);
            }
        }
        
        if(lineItemsToUpdateLst.size() > 0)
            update lineItemsToUpdateLst;
        
    }

}