force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Detail</label>
    <nameField>
        <label>Passengers Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger_Details__c/fields/Nationalities__c.field-meta.xml
<CustomField>
    <fullName>Nationalities__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghan</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Algerian</fullName>
    </customValue>
    <customValue>
        <fullName>American</fullName>
    </customValue>
    <customValue>
        <fullName>Andorran</fullName>
    </customValue>
    <customValue>
        <fullName>Angolan</fullName>
    </customValue>
    <customValue>
        <fullName>Antiguan or Barbudan</fullName>
    </customValue>
    <customValue>
        <fullName>Argentine</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Australian</fullName>
    </customValue>
    <customValue>
        <fullName>Austrian</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijani</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamian</fullName>
    </customValue>
    <customValue>
        <fullName>Bahraini</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladeshi</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian</fullName>
    </customValue>
    <customValue>
        <fullName>Belizean</fullName>
    </customValue>
    <customValue>
        <fullName>Beninese</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutanese</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivian</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnian</fullName>
    </customValue>
    <customValue>
        <fullName>Brazilian</fullName>
    </customValue>
    <customValue>
        <fullName>British</fullName>
    </customValue>
    <customValue>
        <fullName>Bruneian</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Burundian</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodian</fullName>
    </customValue>
    <customValue>
        <fullName>Cameroonian</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomPicklistController.cls
public with sharing class CustomPicklistController {
    @AuraEnabled(cacheable=true)
    public static List<String> getNationalityPicklistValues() {
        // Get the picklist values for the custom field "Nationality" on the Contact object
        List<Schema.PicklistEntry> picklistEntries = Schema.SObjectType.Passenger_Details__c.fields.Nationalities__c.getPicklistValues();
        
        // Create a list to store the values
        List<String> picklistValues = new List<String>();

        for (Schema.PicklistEntry entry : picklistEntries) {
            picklistValues.add(entry.getLabel()); // Add the label to the list
        }

        return picklistValues;
    }
}