force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Airport Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <label>Airport Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Flight_Type__c.field-meta.xml
<CustomField>
    <fullName>Flight_Type__c</fullName>
    <label>Flight Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Flight_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector</label>
    <referenceTo>Sector__c</referenceTo>
    <relationshipLabel>Airports</relationshipLabel>
    <relationshipName>Airports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__mdt/Package__mdt.object-meta.xml
<CustomObject>
    <label>Package</label>
    <pluralLabel>Packages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Package__mdt/fields/Flight_Type__c.field-meta.xml
<CustomField>
    <fullName>Flight_Type__c</fullName>
    <label>Flight Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
                <default>true</default>
                <label>Domestic</label>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Domestic to International</fullName>
            </value>
            <value>
                <fullName>International to Domestic</fullName>
            </value>
            <value>
                <fullName>Domestic to Domestic</fullName>
            </value>
            <value>
                <fullName>International to International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__mdt/fields/Package_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Type__c</fullName>
    <label>Package Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
                <default>true</default>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__mdt</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Package__mdt/fields/Service_Airport__c.field-meta.xml
<CustomField>
    <fullName>Service_Airport__c</fullName>
    <label>Service Airport</label>
    <referenceTo>Service_Airport__mdt</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Package__mdt/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Departure</fullName>
                <default>true</default>
                <label>Departure</label>
            </value>
            <value>
                <fullName>Arrival</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Detail</label>
    <nameField>
        <label>Passengers Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger_Details__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Individual_Booking_Details__c.field-meta.xml
<CustomField>
    <fullName>Individual_Booking_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Booking Details</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Passenger Details</relationshipLabel>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Nationalities__c.field-meta.xml
<CustomField>
    <fullName>Nationalities__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Type__c</fullName>
    <label>Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Infant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Passport_Govt_Id__c.field-meta.xml
<CustomField>
    <fullName>Passport_Govt_Id__c</fullName>
    <label>Passport/Govt Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_Class__c.field-meta.xml
<CustomField>
    <fullName>Travel_Class__c</fullName>
    <label>Travel Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_PNR_No__c.field-meta.xml
<CustomField>
    <fullName>Travel_PNR_No__c</fullName>
    <label>Travel PNR No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placard__c/Placard__c.object-meta.xml
<CustomObject>
    <description>To store placard details of the passenger</description>
    <label>Placard</label>
    <nameField>
        <label>Placard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Placard__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Placards</relationshipLabel>
    <relationshipName>Placards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placard__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sector__c/Sector__c.object-meta.xml
<CustomObject>
    <label>Sector</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Sector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sector__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__mdt/Service__mdt.object-meta.xml
<CustomObject>
    <label>Service</label>
    <pluralLabel>Services</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service__mdt/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <label>Service Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Airport__mdt/Service_Airport__mdt.object-meta.xml
<CustomObject>
    <label>Service Airport</label>
    <pluralLabel>Service Airports</pluralLabel>
</CustomObject>

force-app/main/default/objects/Terminal__c/Terminal__c.object-meta.xml
<CustomObject>
    <label>Terminal</label>
    <nameField>
        <label>Terminal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terminals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terminal__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Terminals</relationshipLabel>
    <relationshipName>Terminals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Terminal__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terminal 1</fullName>
            </value>
            <value>
                <fullName>Terminal 2</fullName>
            </value>
            <value>
                <fullName>Terminal 3</fullName>
            </value>
            <value>
                <fullName>Terminal 4</fullName>
            </value>
            <value>
                <fullName>Terminal 5</fullName>
            </value>
            <value>
                <fullName>Terminal 3I</fullName>
            </value>
            <value>
                <fullName>Terminal 3D</fullName>
            </value>
            <value>
                <fullName>Terminal 2D</fullName>
            </value>
            <value>
                <fullName>Terminal 1D</fullName>
            </value>
            <value>
                <fullName>Terminal 1I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_History__c/Transaction_History__c.object-meta.xml
<CustomObject>
    <description>This object will store all the transactions details done by the customer</description>
    <label>Transaction History</label>
    <nameField>
        <label>Transaction History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_History__c/fields/Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Id__c</fullName>
    <label>Booking Id</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transaction History</relationshipLabel>
    <relationshipName>Transaction_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_History__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Flight_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <masterLabel>Flight Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghan</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Algerian</fullName>
    </customValue>
    <customValue>
        <fullName>American</fullName>
    </customValue>
    <customValue>
        <fullName>Andorran</fullName>
    </customValue>
    <customValue>
        <fullName>Angolan</fullName>
    </customValue>
    <customValue>
        <fullName>Antiguan or Barbudan</fullName>
    </customValue>
    <customValue>
        <fullName>Argentine</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Australian</fullName>
    </customValue>
    <customValue>
        <fullName>Austrian</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijani</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamian</fullName>
    </customValue>
    <customValue>
        <fullName>Bahraini</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladeshi</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian</fullName>
    </customValue>
    <customValue>
        <fullName>Belizean</fullName>
    </customValue>
    <customValue>
        <fullName>Beninese</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutanese</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivian</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnian</fullName>
    </customValue>
    <customValue>
        <fullName>Brazilian</fullName>
    </customValue>
    <customValue>
        <fullName>British</fullName>
    </customValue>
    <customValue>
        <fullName>Bruneian</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Burundian</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodian</fullName>
    </customValue>
    <customValue>
        <fullName>Cameroonian</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PackageSelectionController.cls
public with sharing class PackageSelectionController {

    // Get products from the PricebookEntry for the Standard Pricebook (Gold, Silver, Elite, and Add-Ons)
    @AuraEnabled
    public static List<PackageWrapper> getPackages(String oppId) {
        Map<String,List<String>> packageToServiceMap = new Map<String,List<String>>();
        if (String.isBlank(oppId)) {
            throw new AuraHandledException('Please link an airport');
        }
        Opportunity opp = [
            SELECT Id,Service_Airport__c,Sector__c,Service_Type__c,Flight_Type__c
            FROM Opportunity
            WHERE Id=:oppId
            LIMIT 1
            ];
        List<PackageWrapper> packageColumns = new List<PackageWrapper>();

        List<Package__mdt> packageRecordList = 
            [SELECT  Flight_Type__c, Package_Type__c, Service__r.Service_Name__c,
            Service_Airport__r.MasterLabel, Service_Type__c
            FROM Package__mdt 
            WHERE Service_Airport__r.MasterLabel =:opp.Service_Airport__c
            AND (Flight_Type__c=:opp.Flight_Type__c
            OR Flight_Type__c ='Both')
            AND Service_Type__c =:opp.Service_Type__c
            ];

        // Iterate over package records and access fields
        for (Package__mdt pckg : packageRecordList) {
            if (!packageToServiceMap.containsKey(pckg.Package_Type__c)) {
                packageToServiceMap.put(pckg.Package_Type__c, new List<String>());
            }
            packageToServiceMap.get(pckg.Package_Type__c).add(pckg.Service__r.Service_Name__c);
        }

        List<PricebookEntry> pricebookEntries = [
            SELECT Id, Product2Id, Product2.Name, Product2.Family, Product2.Package_Is_For__c, UnitPrice, Pricebook2Id
            FROM PricebookEntry
            WHERE Pricebook2.IsActive = true
            AND Pricebook2.IsStandard = true
            AND Product2.Family IN ('Gold', 'Silver', 'Elite','Transit')
            AND product2.Airport__r.Airport_Code__c =:opp.Service_Airport__c
            AND product2.Flight_Type__c =:opp.Flight_Type__c
            AND Product2.Service_Type__c =:opp.Service_Type__c
            ORDER BY Product2.Package_Is_For__c, UnitPrice
        ];
        Map<String, ChildWrapper> adultToChildPriceBookMap = new Map<String, ChildWrapper>();
        Map<String, InfantWrapper> adultToInfantPriceBookMap = new Map<String, InfantWrapper>();
        for (PricebookEntry pbEntry : pricebookEntries) {
            
            List<String> allServices = new List<String>(packageToServiceMap.get('All'));
            List<String> specificService = new List<String>(packageToServiceMap.get(pbEntry.Product2.Family));
            List<String> combineService = new List<String>();
            combineService.addall(allServices);
            combineService.addall(specificService);
            PackageWrapper pckg = new PackageWrapper();
            
            pckg.packageName = pbEntry.Product2.Name;
            pckg.productId =  pbEntry.Product2Id;
            pckg.pricebookId = pbEntry.Pricebook2Id;
            pckg.showPackage = false;
            pckg.packageFamily = pbEntry.Product2.Family;
            if(pbEntry.Product2.Package_Is_For__c == 'Adult') {
                pckg.pricebookEntryId = pbEntry.Id;
                pckg.showPackage = true;
                pckg.priceTag = pbEntry.UnitPrice;
                adultToChildPriceBookMap.put(pbEntry.Product2.Family, null);
                adultToInfantPriceBookMap.put(pbEntry.Product2.Family,null);
            } else if(pbEntry.Product2.Package_Is_For__c == 'Child') {
                if(adultToChildPriceBookMap.containsKey(pbEntry.Product2.Family)) {
                    ChildWrapper wrp = new ChildWrapper();
                    wrp.priceBookEntryId = pbEntry.Id;
                    wrp.price = pbEntry.UnitPrice;
                    adultToChildPriceBookMap.put(pbEntry.Product2.Family,wrp);
                }
            } else if(pbEntry.Product2.Package_Is_For__c == 'Infant') {
                if(adultToInfantPriceBookMap.containsKey(pbEntry.Product2.Family)) {
                    InfantWrapper wrp = new InfantWrapper();
                    wrp.priceBookEntryId = pbEntry.Id;
                    wrp.price = pbEntry.UnitPrice;
                    adultToInfantPriceBookMap.put(pbEntry.Product2.Family,wrp);
                }
            }
            pckg.services = combineService; 
            pckg.childPackageWrapper = adultToChildPriceBookMap;
            pckg.infantPackageWrapper = adultToInfantPriceBookMap;            

            packageColumns.add(pckg);
        }  
        System.debug('pack>> '+packageColumns);    
        return packageColumns;
    }

    @AuraEnabled
    public static List<AddonWrapper> getAddons(String oppId) {
        Map<String,List<String>> packageToServiceMap = new Map<String,List<String>>();
        if (String.isBlank(oppId)) {
            throw new AuraHandledException('Please link an airport');
        }
        Opportunity opp = [
            SELECT Id,Service_Airport__c,Sector__c,Service_Type__c,Flight_Type__c
            FROM Opportunity
            WHERE Id=:oppId
            LIMIT 1
            ];
        List<AddonWrapper> addOnColumns = new List<AddonWrapper>();
        
        /*
        List<String> listOfTerminals = new List<String>();
        List<Terminal__c> terminals = [SELECT Id,Code__c from Terminal__c WHERE Airport__r.Airport_Code__c =:opp.Service_Airport__c];
        if (terminals!=null && terminals.size()>0) {
            for (Terminal__c terminal : terminals) {
                AddonWrapper pckg = new AddonWrapper();
                listOfTerminals.add(terminal.Code__c);
                pckg.terminals = listOfTerminals;
                addOnColumns.add(pckg);
            }
        }*/

        List<PricebookEntry> pricebookAddonEntries = [
            SELECT Id, Product2Id, Product2.Name, Product2.Family, UnitPrice, Pricebook2Id
            FROM PricebookEntry
            WHERE Pricebook2.IsActive = TRUE
            AND Pricebook2.IsStandard = TRUE
            AND Product2.Family = 'Add Ons'
            AND product2.Airport__r.Airport_Code__c =:opp.Service_Airport__c
            AND product2.Flight_Type__c =:opp.Flight_Type__c
            AND Product2.Service_Type__c =:opp.Service_Type__c
            ORDER BY UnitPrice
        ];
        if(pricebookAddonEntries.size()<1){
            return null;
        }
        for (PricebookEntry pbEntry : pricebookAddonEntries) {
            AddonWrapper pckg = new AddonWrapper();
            pckg.addOnName = pbEntry.Product2.Name;
            pckg.addOnTag = pbEntry.UnitPrice;   
            pckg.productId =  pbEntry.Product2Id;
            pckg.pricebookEntryId =  pbEntry.Id; 
            pckg.pickupTerminal = getFlightTerminalInfo(oppId);
            pckg.dropTerminal = getDropTerminalInfo(oppId);
            addOnColumns.add(pckg);
        }      

        return addOnColumns;
    }

    @AuraEnabled
        public static List<Terminal__c> getTerminalInfo(String oppId){

            Opportunity opp = [
            SELECT Id,Service_Airport__c,Sector__c,Service_Type__c,Flight_Type__c
            FROM Opportunity
            WHERE Id=:oppId
            LIMIT 1
            ];

        List<Terminal__c> terminals = [SELECT Id,Code__c from Terminal__c WHERE Airport__r.Airport_Code__c =:opp.Service_Airport__c ORDER BY Code__c];
        
            return terminals;
        }
        @AuraEnabled
        public static String getFlightTerminalInfo(String oppId) {
            Id terminalId;
            Opportunity opp = [
            SELECT Id,Arriving_Flight_Schedule__c,Departure_Flight_Schedule__c,
            Departure_Flight_Schedule__r.Departure_Terminal__c,
            Arriving_Flight_Schedule__r.Arrival_Terminal__c
            FROM Opportunity
            WHERE Id=:oppId
            LIMIT 1
            ];
            if (opp.Arriving_Flight_Schedule__c !=null) {
                terminalId = opp.Arriving_Flight_Schedule__r.Arrival_Terminal__c;
                Terminal__c terminal = [SELECT Id,Code__c from Terminal__c WHERE Id=: terminalId LIMIT 1];    
                return terminal.Code__c!=null ? terminal.Code__c : '';
            } else if (opp.Departure_Flight_Schedule__c !=null){
                terminalId= opp.Departure_Flight_Schedule__r.Departure_Terminal__c;
                Terminal__c terminal = [SELECT Id,Code__c from Terminal__c WHERE Id=: terminalId LIMIT 1]; 
                return terminal.Code__c!=null ? terminal.Code__c : ''; 
            }
            return '';
        }
        @AuraEnabled
        public static String getDropTerminalInfo(String oppId) {
            Id terminalId;
            Opportunity opp = [
            SELECT Id,Arriving_Flight_Schedule__c,Departure_Flight_Schedule__c,
            Departure_Flight_Schedule__r.Departure_Terminal__c,
            Arriving_Flight_Schedule__r.Arrival_Terminal__c
            FROM Opportunity
            WHERE Id=:oppId
            LIMIT 1
            ];
            if (opp.Departure_Flight_Schedule__c !=null && opp.Departure_Flight_Schedule__r.Departure_Terminal__c!=null){
                terminalId= opp.Departure_Flight_Schedule__r.Departure_Terminal__c;
                Terminal__c terminal = [SELECT Id,Code__c from Terminal__c WHERE Id=: terminalId LIMIT 1]; 
                return terminal.Code__c!=null ? terminal.Code__c : ''; 
            }
            return '';
        }

    @AuraEnabled
    public static passengerWrapper getOpportunityDetails(Id opportunityId) {
        // Fetch Opportunity record with related fields for adults, children, and infants
        Opportunity opp =  [SELECT Id, 
                       Number_of_Adults__c, 
                       Number_of_Children__c, 
                       Number_of_Infants__c,
                       Date_of_Arrival__c,
                       Date_of_Departure__c,
                       Service_Airport__c,
                       Flight_Number_Arrival__c,
                       Service_Type__c,
                       Flight_Number_Departure__c,(SELECT Id FROM OpportunityLineItems)
                FROM Opportunity 
                WHERE Id = :opportunityId 
                LIMIT 1];
        passengerWrapper pasWrp = new passengerWrapper();
        pasWrp.NoOfAdult = opp.Number_of_Adults__c;
        pasWrp.NoOfChild = opp.Number_of_Children__c;
        pasWrp.NoOfInfant = opp.Number_of_Infants__c;
        pasWrp.serviceAirport = opp.Service_Airport__c;
        pasWrp.flightNumber = opp.Service_Type__c =='Transit' ? opp.Flight_Number_Arrival__c + ' / '+ opp.Flight_Number_Departure__c : opp.Flight_Number_Arrival__c != null ? 
                                opp.Flight_Number_Arrival__c : 
                                opp.Flight_Number_Departure__c != null ?
                                opp.Flight_Number_Departure__c : '';                                
        pasWrp.flightDate = opp.Service_Type__c =='Transit' ?  opp.Date_of_Arrival__c + ' / '+ opp.Date_of_Departure__c : opp.Date_of_Arrival__c != null ? 
                                opp.Date_of_Arrival__c : 
                                opp.Date_of_Departure__c != null ?
                                opp.Date_of_Departure__c : '';
        return pasWrp;
    }

    @AuraEnabled
    public static void savePassengerDetails(List<Map<String, Object>> passengerData, Id opportunityId) {
        List<Passenger_Details__c> passengerDetailsList = new List<Passenger_Details__c>();
        // Create a Map directly from the query result
        Map<Id, String> opportunityMap = new Map<Id, String>();// Initialize a Map to store Record_Id__c as key and Description__c as value
        List<OpportunityLineItem> oliList = [SELECT Id,Product2.Package_Is_For__c 
            FROM OpportunityLineItem
            WHERE OpportunityId =:opportunityId
            AND Status__c = 'Active'
            AND Id NOT IN (
                SELECT Individual_Booking_Details__c
                FROM Passenger_Details__c
            )
            ORDER BY CreatedDate DESC];
        //Delete existing passengers and create new list if updates are made
        List<Passenger_Details__c> passengersToDelete = [SELECT Id FROM Passenger_Details__c WHERE Opportunity_ID__c=:opportunityId];
        /*
        if (passengersToDelete!=null && passengersToDelete.size()>0) {
            Delete passengersToDelete;
        } */
        Map<String, String> typeToOliIdMap = new Map<String, String>();
        // Create a map to store lists of passengers by their 'Valid_For' field value
        Map<String, List<Id>> oliMap = new Map<String, List<Id>>();
        // Iterate over the OpportunityLineItem object records and populate the map
        for (OpportunityLineItem oli : oliList) {
            //typeToOliIdMap.put(oli.Product2.Package_Is_For__c, oli.Id);
            if (!oliMap.containsKey(oli.Product2.Package_Is_For__c)) {
            	oliMap.put(oli.Product2.Package_Is_For__c, new List<Id>());
        	}
        	oliMap.get(oli.Product2.Package_Is_For__c).add(oli.Id);
        }
        for (Map<String, Object> guest : passengerData) {
            Passenger_Details__c passenger = new Passenger_Details__c();
            passenger.Name = (String) guest.get('firstname') + ' ' + (String) guest.get('lastname');
            passenger.Opportunity_ID__c = opportunityId;
            passenger.Title__c = (String) guest.get('title');
            passenger.First_Name__c = (String) guest.get('firstname');
            passenger.Last_Name__c = (String) guest.get('lastname');
            passenger.Gender__c = (String) guest.get('gender');
            String ageStr = (String) guest.get('age');
    		Integer age =  ageStr != null ? Integer.valueOf(ageStr) : null;  // Convert the String to Integer
   			passenger.Age__c = age;
            passenger.Designation__c = (String) guest.get('designation');
            passenger.Travel_Class__c = (String) guest.get('travelclass');
            passenger.Travel_PNR_No__c = (String) guest.get('travelpnrno');
            passenger.Designation__c = (String) guest.get('designation');
            passenger.Nationalities__c = (String) guest.get('nationality');
            passenger.Passport_Govt_Id__c = (String) guest.get('passportnumber');
            passenger.Mobile__c = (String) guest.get('phone');
            passenger.Passenger_Type__c = (String) guest.get('type');
            if(oliMap.containsKey((String) guest.get('type'))) {
               List<Id> oliIds = oliMap.get((String) guest.get('type'));
                if (!oliIds.isEmpty()) {
                // Get the first Id from the list
                Id oliId = oliIds[0];
                
                // Now, link this Passenger_Details__c record to the OpportunityLineItem
                passenger.Individual_Booking_Details__c = oliId;
                
                // Remove the used Id from the list
                oliIds.remove(0);
                
                // If the list is now empty, remove the key from the map to avoid future checks
                if (oliIds.isEmpty()) {
                    oliMap.remove((String) guest.get('type'));
                }
            }
            }
            passengerDetailsList.add(passenger);
        }
        // Insert the Opportunity Line Items
        try { 
            insert passengerDetailsList;
        } catch (Exception e) {
            System.debug('Error inserting Passenger_Details__c records: ' + e.getMessage());
            throw new AuraHandledException('Error in creating guest data, please show this message to admin');
        }
    }

    @AuraEnabled
    public static void savePlacardDetails(List<Map<String, Object>> placardData, Id opportunityId) {
        List<Placard__c> placardList = new List<Placard__c>();
        
        for (Map<String, Object> guest : placardData) {
            Placard__c plc = new Placard__c();
            plc.Name = (String) guest.get('firstname') + ' ' + (String) guest.get('lastname');
            plc.Opportunity_ID__c = opportunityId;
            plc.Title__c = (String) guest.get('title');
            plc.First_Name__c = (String) guest.get('firstname');
            plc.Last_Name__c = (String) guest.get('lastname');
            plc.Mobile_Number__c = (String) guest.get('phone');
            
            placardList.add(plc);
        }
        try { 
            insert placardList;
        } catch (Exception e) {
            System.debug('Error inserting Placard__c records: ' + e.getMessage());
            throw new AuraHandledException('Error in creating Placard data, please show this message to admin');
        }
    }


    // Method to create Opportunity Line Items
    @AuraEnabled
    public static void createOpportunityLineItems(Id opportunityId, List<Map<String, Object>> productDetails, Decimal amount) {
        // Create a list to store OpportunityLineItems
        List<OpportunityLineItem> opportunityLineItemsToInsert = new List<OpportunityLineItem>();
        List<Transaction_History__c> transactionList= new List<Transaction_History__c>();
        Decimal totalListPrice=0;

        // Query Opportunity based on OpportunityId
        Opportunity opp = [
            SELECT Name
            FROM Opportunity
            WHERE Id=:opportunityId
            LIMIT 1
        ];

        //update opportunity
        /*
        List<OpportunityLineItem> loiToDelete = [SELECT Id,Product2Id FROM OpportunityLineItem WHERE OpportunityId =:opportunityId];
        Delete loiToDelete;
        */
        for (Map<String, Object> productDetail : productDetails) {
            // Extract the values from the map
            Id productId = (Id) productDetail.get('productId');
            Id pricebookEntry = (Id) productDetail.get('pricebookEntryId');
            Decimal quantity = (Boolean) productDetail.get('isChild') ? (Decimal) productDetail.get('childCount') : (Decimal) productDetail.get('count');
            Decimal unitPrice = (Decimal) productDetail.get('unitPrice');
            String pickupTerminal = (String) productDetail.get('pickup');
            String dropTerminal = (String) productDetail.get('drop'); 
            
            for (Integer i=0; i<quantity; i++) {
                // Create a new Opportunity Line Item
                OpportunityLineItem oli = new OpportunityLineItem();
                oli.OpportunityId = opportunityId;
                oli.Product2Id = productId;
                oli.Quantity = 1;
                oli.UnitPrice = unitPrice;
                oli.PricebookEntryId = pricebookEntry; // Link PricebookEntry to OLI
                oli.Pickup_Terminal__c = pickupTerminal;
                oli.Drop_Terminal__c = dropTerminal;
                oli.Status__c = 'Active';
                totalListPrice += unitPrice;
                // Add the OLI to the list
                opportunityLineItemsToInsert.add(oli);
            }
        }
            //creation of transaction record for booking
            if(totalListPrice !=0) {
                Transaction_History__c transactionRec= new Transaction_History__c();
                transactionRec.Booking_Id__c = opportunityId;
                transactionRec.List_Price__c = totalListPrice;
                transactionRec.Name = opp.Name;
                transactionRec.Transaction_Type__c = 'Debit';
                
                transactionList.add(transactionRec);
            } 

        // Insert the Opportunity Line Items
        try {
            insert opportunityLineItemsToInsert;                
            insert transactionList;
        } catch (Exception e) {
            System.debug('Error inserting Opportunity Line Items: ' + e.getMessage());
            throw new AuraHandledException('Error in creating order summary, please show this message to admin');
        }
    }

    public class PackageWrapper {
        @AuraEnabled
        public String packageName;
        @AuraEnabled
        public Decimal priceTag;
        @AuraEnabled
        public Id productId;
        @AuraEnabled
        public Id pricebookEntryId;
        @AuraEnabled
        public Id pricebookId;
        @AuraEnabled
        public Map<String, ChildWrapper> childPackageWrapper;
        @AuraEnabled
        public Map<String, InfantWrapper> infantPackageWrapper;
        @AuraEnabled
        public Boolean showPackage;
        @AuraEnabled
        public List<String> services {get;set;}
        @AuraEnabled
        public String packageFamily;

    }
    public class ChildWrapper {
        @AuraEnabled
        public String priceBookEntryId;
        @AuraEnabled
        public Decimal price;
    }
    public class InfantWrapper {
        @AuraEnabled
        public String priceBookEntryId;
        @AuraEnabled
        public Decimal price;
    }
    public class AddonWrapper {
        @AuraEnabled
        public String addOnName;
        @AuraEnabled
        public Decimal addOnTag;
        @AuraEnabled
        public Id productId;
        @AuraEnabled
        public Id pricebookEntryId;
        @AuraEnabled
        public String pickupTerminal;
        @AuraEnabled
        public String dropTerminal;
    }
    public class passengerWrapper {
        @AuraEnabled
        public Decimal NoOfAdult;
        @AuraEnabled
        public Decimal NoOfChild;
        @AuraEnabled
        public Decimal NoOfInfant;
        @AuraEnabled
        public String serviceAirport;
        @AuraEnabled
        public String flightNumber;
        @AuraEnabled
        public String flightDate;
    }
}