force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Airport Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/Airport_Name__c.field-meta.xml
<CustomField>
    <fullName>Airport_Name__c</fullName>
    <label>Airport Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Country_Id__c.field-meta.xml
<CustomField>
    <fullName>Country_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Id</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Airports</relationshipLabel>
    <relationshipName>Airports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <formula>Location_Id__r.Location_Code__c + &apos;-&apos; +  Airport_Name__c  + &apos; (&apos; +  Location_Id__r.City__c  + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Id</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Airports</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Service_Available__c.field-meta.xml
<CustomField>
    <fullName>Service_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/State_Id__c.field-meta.xml
<CustomField>
    <fullName>State_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State Id</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Airports</relationshipLabel>
    <relationshipName>Airports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Country_Id__c.field-meta.xml
<CustomField>
    <fullName>Country_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Id</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <label>Location Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State_Id__c.field-meta.xml
<CustomField>
    <fullName>State_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State Id</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <label>State Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDEN_GetAllAirportLocationsMasterData.cls
/* Created by 	: Maxify Development Team
 * Created Date : 14th Jan, 2025
 * Input 		: Airport id in JSON format
 * Purpose 		: This API class returns all the airport locations for a particular airport
 */
@RestResource(urlMapping='/get_all_airport/*')  
global class MDEN_GetAllAirportLocationsMasterData {
    @HttpGet
    global static MDEN_GetResponseWrapper getAiportLocations(){
        //Initialize the response wrapper with blank status and blank message
		MDEN_GetResponseWrapper mden_responseWrapper = new MDEN_GetResponseWrapper('', '');
        try{
            //Uncomment below to call via Postman
            /*RestRequest request = RestContext.request;
            Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(request.requestbody.toString());
            */
            //Uncomment below to call via Developer console using : MDEN_GetAllAirportLocationsMasterData.getAiportLocations();
            String reqBody =' { ' +
                            ' "airport_id" : "Indira Gandhi International Airport"' +
                            ' } ';  
			Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(reqBody);
            
            
            system.debug('requestMap==>'+requestMap.get('airport_id'));
            
            //Parsing data from requestMap
            String airportId = (String)requestMap.get('airport_id');
            
            List<Airport__c>  airportList = [select id,
                                                    name,
                                                    Airport_Name__c,
                                                    Display_Name__c,
                                                    Location_Id__r.name,
                                                    Location_Id__r.Location_Code__c,
                                                    Location_Id__r.City__c,
                                                    State_Id__r.name,
                                                    State_Id__r.State_name__c,
                                                    Service_Available__c,
                                                    City__c,
                                                    Country_Id__r.name,
                                                    Country_Id__r.Country_name__c 
                                             from Airport__c 
                                             where Airport_Name__c = :airportId AND 
                                             	   Service_Available__c = true];
            
            	system.debug('airportList==>'+airportList);
            
            	//Null check for the airport list
                if(airportList <> null && airportList.size() >= 0){
                    //Initialize the wrapper with status and message
                    mden_responseWrapper = new MDEN_GetResponseWrapper('true', 'data found.');
                    List<AirportWrapper> datalist = new List<AirportWrapper>();
                        
                    for(Airport__c airport: airportList){
                        AirportWrapper airportWrap = new AirportWrapper();
                        airportWrap.id = airport.name;
                        airportWrap.name = airport.Airport_Name__c;
                        airportWrap.airport_location_code_id = (airport.Location_Id__c <> null) ? new List<String>{airport.Location_Id__r.name, airport.Location_Id__r.Location_Code__c} : new List<String>{'', ''};
                        airportWrap.city = (airport.Location_Id__c <> null) ? airport.Location_Id__r.City__c : '';
                        airportWrap.country_id = (airport.Country_Id__c <> null) ? new List<String>{airport.Country_Id__r.name, airport.Country_Id__r.Country_name__c} : new List<String>{'', ''};
                        airportWrap.state_id = (airport.State_Id__c <> null) ? airport.State_Id__r.name : '';
                        airportWrap.display_name = airport.Display_Name__c;
                      
                        datalist.add(airportWrap);
                    }
                    mden_responseWrapper.datalist = datalist;
                    
                    system.debug('mden_responseWrapper==>'+JSON.serialize(mden_responseWrapper));
            }
            else{
                mden_responseWrapper = new MDEN_GetResponseWrapper('false', 'data not found.');
            }
        }
         catch(Exception e){
            mden_responseWrapper = new MDEN_GetResponseWrapper('false', e.getMessage());
        }
		
		return mden_responseWrapper;
    }
     global class MDEN_GetResponseWrapper {
        global String status; 
        global String message;
        global List<AirportWrapper> datalist;
        global MDEN_GetResponseWrapper(String status, String message) {
            this.status = status;
            this.message = message; 
        }        
    }
    global class AirportWrapper{
        global string id;
        global string name;
        global List<String> airport_location_code_id;
        global string city;
        global List<String> country_id;
        global string state_id;
        global string display_name;
        
        global AirportWrapper(){
            
        }
    }
}