force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Airport Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <label>Airport Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Flight_Type__c.field-meta.xml
<CustomField>
    <fullName>Flight_Type__c</fullName>
    <label>Flight Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Flight_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Service_Available__c.field-meta.xml
<CustomField>
    <fullName>Service_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Detail</label>
    <nameField>
        <label>Passengers Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger_Details__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Nationalities__c.field-meta.xml
<CustomField>
    <fullName>Nationalities__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Type__c</fullName>
    <label>Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Infant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Passport_Govt_Id__c.field-meta.xml
<CustomField>
    <fullName>Passport_Govt_Id__c</fullName>
    <label>Passport/Govt Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Show_as_Placard__c.field-meta.xml
<CustomField>
    <fullName>Show_as_Placard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show as Placard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_Class__c.field-meta.xml
<CustomField>
    <fullName>Travel_Class__c</fullName>
    <label>Travel Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_PNR_No__c.field-meta.xml
<CustomField>
    <fullName>Travel_PNR_No__c</fullName>
    <label>Travel PNR No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placard__c/Placard__c.object-meta.xml
<CustomObject>
    <description>To store placard details of the passenger</description>
    <label>Placard</label>
    <nameField>
        <label>Placard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Placard__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Placards</relationshipLabel>
    <relationshipName>Placards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placard__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_History__c/Transaction_History__c.object-meta.xml
<CustomObject>
    <description>This object will store all the transactions details done by the customer</description>
    <label>Transaction History</label>
    <nameField>
        <label>Transaction History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_History__c/fields/Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Id__c</fullName>
    <label>Booking Id</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transaction History</relationshipLabel>
    <relationshipName>Transaction_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Flight_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <masterLabel>Flight Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nationality.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghan</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Algerian</fullName>
    </customValue>
    <customValue>
        <fullName>American</fullName>
    </customValue>
    <customValue>
        <fullName>Andorran</fullName>
    </customValue>
    <customValue>
        <fullName>Angolan</fullName>
    </customValue>
    <customValue>
        <fullName>Antiguan or Barbudan</fullName>
    </customValue>
    <customValue>
        <fullName>Argentine</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Australian</fullName>
    </customValue>
    <customValue>
        <fullName>Austrian</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijani</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamian</fullName>
    </customValue>
    <customValue>
        <fullName>Bahraini</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladeshi</fullName>
    </customValue>
    <customValue>
        <fullName>Barbadian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian</fullName>
    </customValue>
    <customValue>
        <fullName>Belizean</fullName>
    </customValue>
    <customValue>
        <fullName>Beninese</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutanese</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivian</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnian</fullName>
    </customValue>
    <customValue>
        <fullName>Brazilian</fullName>
    </customValue>
    <customValue>
        <fullName>British</fullName>
    </customValue>
    <customValue>
        <fullName>Bruneian</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Burundian</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodian</fullName>
    </customValue>
    <customValue>
        <fullName>Cameroonian</fullName>
    </customValue>
    <customValue>
        <fullName>Indian</fullName>
    </customValue>
    <masterLabel>Nationality</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PackageSelectionControllerTest.cls
@isTest
public class PackageSelectionControllerTest {
    static Id pricebookId;
    
    @testSetUp
    static void setupTestData() {
        // Setup Account
        Account acc = new Account(
            Name = 'Test Account', 
            Surcharge_waived_off__c = false,
            BillingStreet = '123 Main Street',
            BillingCity = 'Pune',
            BillingState = 'Maharashtra',
            BillingPostalCode = '411001',
            BillingCountry = 'India'
        );
        insert acc;
        
        // Setup Opportunity
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(10),
            AccountId = acc.Id,
            Flight_Type__c = 'Domestic',
            Service_Type__c = 'Arrival',
            Date_of_Arrival__c = String.ValueOf(Date.today().addDays(1)),
            STA_Time__c = '10:00',
            Service_Airport__c = 'DEL'
        );
        insert opp;
        Passenger_Details__c passenger = new Passenger_Details__c(
            Title__c = 'Mr',
            First_Name__c = 'John',
            Last_Name__c = 'Doe',
            Gender__c = 'Male',
            Age__c = 35.00, // converted to String
            Designation__c = 'Manager',
            Travel_Class__c = 'Economy',
            Travel_PNR_No__c = 'PNR12345',
            Nationalities__c = 'Indian',
            Passport_Govt_Id__c = 'A12345678',
            Mobile__c = '9778803210',
            Passenger_Type__c = 'Adult',
            Show_as_Placard__c = true,
            Opportunity_ID__c = Opp.Id
        );
        insert passenger;
        Placard__c placard = new Placard__c(
            Opportunity_ID__c = opp.Id,
            Title__c = 'Mr',
            First_Name__c = 'John',
            Last_Name__c = 'Smith',
            Mobile_Number__c = '9876543210'
        );
        insert placard;
        // Setup Product and PricebookEntry
        Airport__c airport = new Airport__c(Name='Delhi', Airport_Code__c= Opp.Service_Airport__c, Type__c='International', Country__c='India', Service_Available__c=true);
        insert airport;
        
        Product2 prod = new Product2(
            Name = 'Test Product',
            Flight_Type__c = Opp.Flight_Type__c, 
            Service_Type__c = Opp.Service_Type__c, 
            Family = 'Gold', 
            Airport__c = airport.id ,
            Package_Is_For__c = 'Adult'
        );
        insert prod;
        
        Product2 prodSurcharge = new Product2(
            Name = 'Surcharge Product',
            Flight_Type__c = Opp.Flight_Type__c, 
            Service_Type__c = Opp.Service_Type__c, 
            Family = 'Surcharge', 
            Airport__c = airport.id ,
            Package_Is_For__c = 'Adult'
        );
        insert prodSurcharge;
        
        pricebookId = Test.getStandardPricebookId();
        
        /*Pricebook2 pb = [SELECT Id, IsActive FROM Pricebook2 WHERE Id = :pricebookId];
pb.IsActive = true;
update pb;*/
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 500,
            IsActive = true
        );
        insert pbe;
        
        PricebookEntry surchargePbe = new PricebookEntry(
        Pricebook2Id = pricebookId,
        Product2Id = prodSurcharge.Id,
        UnitPrice = 50,
        IsActive = true,
        List_Price_In_Percentage__c = false
        );
        insert surchargePbe;
        // Create OpportunityLineItems
        OpportunityLineItem oli1 = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = 1,
            UnitPrice = 1000,
            PricebookEntryId = pbe.Id,
            Status__c = 'Active'
        );
        insert oli1;
    }
    @isTest
    static void testCreateOpportunityLineItems(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        Product2 prod = [Select Id From Product2 Where Name = 'Test Product'  Limit 1];
        PricebookEntry pbe = [Select Id From PricebookEntry Where UnitPrice = 500 Limit 1 ];
        // Sample productDetails map
        List<Map<String, Object>> productDetails = new List<Map<String, Object>>();
        Map<String, Object> detail = new Map<String, Object>{
            'productId' => prod.Id,
                'pricebookEntryId' => pbe.Id,
                'count' => 2,
                'unitPrice' => 500,
                'discountValue' => 100,
                'isChild' => false,
                'pickupTerminals' => new List<String>{ 'T1' },
                    'dropTerminals' => new List<String>{ 'T2' }
        };
            productDetails.add(detail);
        
        // Call the method
        Test.startTest();
        PackageSelectionController.createOpportunityLineItems(opp.Id, productDetails, 1000);
        Test.stopTest();
        
        // Assertions
        List<OpportunityLineItem> olis = [SELECT Id, OpportunityId FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assert(olis.size() > 0, 'OpportunityLineItems should be created');
        
        List<Transaction_History__c> txns = [SELECT Id FROM Transaction_History__c WHERE Booking_Id__c = :opp.Id];
        System.assert(txns.size() > 0, 'Transaction records should be created');
    }
    @isTest
    static void testCreateOpportunityLineItems2(){
        Opportunity opp = [Select Id,Departure_Service_Time__c from Opportunity Limit 1];
        Opp.Departure_Service_Time__c = '12:00';
        Opp.Date_of_Departure__c = String.ValueOf(Date.today().addDays(1));
        Opp.STA_Time__c = null;
        update Opp;
        Product2 prod = [Select Id From Product2 Where Name = 'Test Product'  Limit 1];
        PricebookEntry pbe = [Select Id From PricebookEntry Where UnitPrice = 500 Limit 1 ];
        // Sample productDetails map
        List<Map<String, Object>> productDetails = new List<Map<String, Object>>();
        Map<String, Object> detail = new Map<String, Object>{
            'productId' => prod.Id,
                'pricebookEntryId' => pbe.Id,
                'count' => 2,
                'unitPrice' => 500,
                'discountValue' => 100,
                'isChild' => false,
                'pickupTerminals' => new List<String>{  },
                    'dropTerminals' => new List<String>{  }
        };
            productDetails.add(detail);
        
        // Call the method
        Test.startTest();
        PackageSelectionController.createOpportunityLineItems(opp.Id, productDetails, 1000);
        Test.stopTest();
        
        // Assertions
        List<OpportunityLineItem> olis = [SELECT Id, OpportunityId FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assert(olis.size() > 0, 'OpportunityLineItems should be created');
        
        List<Transaction_History__c> txns = [SELECT Id FROM Transaction_History__c WHERE Booking_Id__c = :opp.Id];
        System.assert(txns.size() > 0, 'Transaction records should be created');
    }
    @isTest
    static void testGetPackages(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        
        // Call the method
        Test.startTest();
        PackageSelectionController.getPackages(opp.Id);
        
        Product2 prod = [Select Id,Package_Is_For__c,Family From Product2 Where Name = 'Test Product'  Limit 1];
        
        prod.Package_Is_For__c = 'Child';
        prod.Family = 'Gold';
        Update prod;
        PackageSelectionController.getPackages(opp.Id);
        
        prod.Package_Is_For__c = 'Infant';
        prod.Family = 'Gold';
        Update prod;
        PackageSelectionController.getPackages(opp.Id);
        
        Test.stopTest();
    }
    @isTest
    static void testGetAddons(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        
        // Call the method
        Test.startTest();
        PackageSelectionController.getAddons(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void testGetFlightTerminalInfo(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        
        // Call the method
        Test.startTest();
        PackageSelectionController.getFlightTerminalInfo(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void getDropTerminalInfoTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        
        // Call the method
        Test.startTest();
        PackageSelectionController.getDropTerminalInfo(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void getOpportunityDetailsTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        
        // Call the method
        Test.startTest();
        PackageSelectionController.getOpportunityDetails(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void getTerminalInfoTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        
        // Call the method
        Test.startTest();
        PackageSelectionController.getTerminalInfo(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void getSavedPassengerDetailsTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];        
        // Call the method
        Test.startTest();
        PackageSelectionController.getSavedPassengerDetails(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void getPlacardDetailsTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];        
        // Call the method
        Test.startTest();
        PackageSelectionController.getPlacardDetails(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void updateBookingStateTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];        
        // Call the method
        Test.startTest();
        PackageSelectionController.updateBookingState(opp.Id,'Delhi');
        Test.stopTest();
    }
    @isTest
    static void updateAddonsOrderSummaryStateTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];        
        // Call the method
        Test.startTest();
        PackageSelectionController.updateAddonsOrderSummaryState(opp.Id,'Test','Test');
        Test.stopTest();
    }
    @isTest
    static void getProcessStateTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];        
        // Call the method
        Test.startTest();
        PackageSelectionController.getProcessState(opp.Id);
        Test.stopTest();
    }
    @isTest
    static void savePlacardDetailsTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];        
        
        List<Map<String, Object>> placardData = new List<Map<String, Object>>();
        placardData.add(new Map<String, Object>{
            'title' => 'Ms.',
                'firstname' => 'Jane',
                'lastname' => 'Doe',
                'phone' => '1234567890'
                });
        placardData.add(new Map<String, Object>{
            'title' => 'Dr.',
                'firstname' => 'John',
                'lastname' => 'Smith',
                'phone' => '9876543210'
                });
        
        Test.startTest();
        PackageSelectionController.savePlacardDetails(placardData, opp.Id);
        Test.stopTest();
        
        List<Placard__c> result = [SELECT First_Name__c, Last_Name__c, Mobile_Number__c FROM Placard__c WHERE Opportunity_ID__c = :opp.Id ];
        
        System.assertEquals(2, result.size(), 'Two new placards should be inserted');
        Set<String> names = new Set<String>();
        for (Placard__c p : result) {
            names.add(p.First_Name__c + ' ' + p.Last_Name__c);
        }
        System.assert(names.contains('Jane Doe'), 'Jane Doe should be inserted');
        System.assert(names.contains('John Smith'), 'John Smith should be inserted');
    }
    @isTest
    static void savePassengerDetailsTest(){
        Opportunity opp = [Select Id from Opportunity Limit 1];
        List<Map<String, Object>> passengerData = new List<Map<String, Object>>();
        
        passengerData.add(new Map<String, Object>{
            'id' => 'P001',
                'title' => 'Mr',
                'firstname' => 'John',
                'lastname' => 'Doe',
                'gender' => 'Male',
                'age' => '30',
                'designation' => 'Manager',
                'travelclass' => 'Economy',
                'travelpnrno' => 'PNR123',
                'nationality' => 'Indian',
                'passportnumber' => 'A12345678',
                'phone' => '9999999999',
                'type' => 'Adult',
                'isPlacard' => true
                });        
        // Call the method
        Test.startTest();
        PackageSelectionController.savePassengerDetails(passengerData, opp.Id);
        Test.stopTest();
        
        // Validate that passenger was inserted
        List<Passenger_Details__c> passengers = [SELECT Id, First_Name__c, Last_Name__c FROM Passenger_Details__c WHERE Opportunity_ID__c = :opp.Id];
        System.assertEquals(1, passengers.size());
        System.assertEquals('John', passengers[0].First_Name__c);
        System.assertEquals('Doe', passengers[0].Last_Name__c);
    }
    @isTest
    static void test_getSurchargeAmount() {
        
        DateTime bookingDateTime = DateTime.now();
        DateTime serviceDateTime = bookingDateTime.addHours(2);  
        
        // Parameters
        Decimal bookingAmount = 1000;
        Decimal percent = 10;  // 10% surcharge
        Decimal fixedAmount = 150;
        
        Test.startTest();
        
        // Case 1: Surcharge in Percent, within allowed hours
        Decimal percentResult = PackageSelectionController.getSurchargeAmount(
            serviceDateTime,
            bookingDateTime,
            percent,
            bookingAmount,
            true
        );
        System.assertEquals(1100, percentResult, 'Expected 10% surcharge added to booking amount');
        
        // Case 2: Surcharge in Fixed Amount, within allowed hours
        Decimal fixedResult = PackageSelectionController.getSurchargeAmount(
            serviceDateTime,
            bookingDateTime,
            fixedAmount,
            bookingAmount,
            false
        );
        System.assertEquals(fixedAmount, fixedResult, 'Expected fixed surcharge amount');
        
        // Case 3: Time exceeds allowed surcharge window — should return 0
        DateTime farFutureService = bookingDateTime.addHours(100); 
        Decimal zeroResult = PackageSelectionController.getSurchargeAmount(
            farFutureService,
            bookingDateTime,
            percent,
            bookingAmount,
            true
        );
        System.assertEquals(0, zeroResult, 'Expected no surcharge beyond allowed time window');
        
        Test.stopTest();
    }    
}