force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Airport Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terminal__c/Terminal__c.object-meta.xml
<CustomObject>
    <label>Terminal</label>
    <nameField>
        <label>Terminal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terminals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terminal__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Terminals</relationshipLabel>
    <relationshipName>Terminals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Terminal__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terminal 1</fullName>
            </value>
            <value>
                <fullName>Terminal 2</fullName>
            </value>
            <value>
                <fullName>Terminal 3</fullName>
            </value>
            <value>
                <fullName>Terminal 4</fullName>
            </value>
            <value>
                <fullName>Terminal 5</fullName>
            </value>
            <value>
                <fullName>Terminal 3I</fullName>
            </value>
            <value>
                <fullName>Terminal 3D</fullName>
            </value>
            <value>
                <fullName>Terminal 2D</fullName>
            </value>
            <value>
                <fullName>Terminal 1D</fullName>
            </value>
            <value>
                <fullName>Terminal 1I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MDEN_GetAirportTerminalByAirport_Test.cls
@isTest
private class MDEN_GetAirportTerminalByAirport_Test {

    // This method will create the necessary data for testing
    static void setupTestData() {
        // Creating a test Airport record
        Airport__c airport = new Airport__c(Name = 'Test Airport');
        insert airport;

        // Creating Terminal records for the test airport
        Terminal__c terminal1 = new Terminal__c(
            Name = 'T1', 
            Airport__c = airport.id, 
            Code__c = 'Terminal 1'
        );
        insert terminal1;

        Terminal__c terminal2 = new Terminal__c(
            Name = 'T2', 
            Airport__c = airport.id, 
            Code__c = 'Terminal 1'
        );
        insert terminal2;
    }

    // Test when terminal records are found
    @isTest
    static void testGetAirportTerminalsSuccess() {
        setupTestData();
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/get_terminal_by_airport/T1';
        req.addHeader('Content-Type', 'application/json');
        req.requestBody = Blob.valueOf('{"airport_code":"T1"}');
        RestContext.request = req;
        Test.startTest();
        MDEN_GetAirportTerminalByAirport.MDEN_GetResponseWrapper response = MDEN_GetAirportTerminalByAirport.getAiportTerminals();
        Test.stopTest();
        System.assertEquals('true', response.status);
        System.assertEquals('data found.', response.message);
     
    }

    // Test when no terminal records are found
    @isTest
    static void testGetAirportTerminalsNoData() {
        // Prepare the mock request
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/get_terminal_by_airport/T3';
        req.addHeader('Content-Type', 'application/json');
        req.requestBody = Blob.valueOf('{"airport_code":"T3"}');
        RestContext.request = req;
        Test.startTest();
        MDEN_GetAirportTerminalByAirport.MDEN_GetResponseWrapper response = MDEN_GetAirportTerminalByAirport.getAiportTerminals();
        Test.stopTest();
        System.assertEquals('false', response.status);
        System.assertEquals('data not found.', response.message);
    }

    // Test when an exception occurs during execution
    @isTest
    static void testGetAirportTerminalsException() {
       
        RestRequest req = new RestRequest();
        req.requestUri = '/services/apexrest/get_terminal_by_airport/T1';
        req.addHeader('Content-Type', 'application/json');
        req.requestBody = Blob.valueOf('{"airport_code":}');
        RestContext.request = req;
        Test.startTest();
        MDEN_GetAirportTerminalByAirport.MDEN_GetResponseWrapper response = MDEN_GetAirportTerminalByAirport.getAiportTerminals();
        Test.stopTest();
        System.assertEquals('false', response.status);
        System.assertNotEquals('data not found.', response.message); 
    }
}