force-app/main/default/objects/Flight_Detail__c/Flight_Detail__c.object-meta.xml
<CustomObject>
    <label>Flight Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Flight Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Detail__c/fields/Airline_Id__c.field-meta.xml
<CustomField>
    <fullName>Airline_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Id</label>
    <referenceTo>Airline__c</referenceTo>
    <relationshipLabel>Flight Details</relationshipLabel>
    <relationshipName>Flight_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipName>Flight_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Arrival_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Terminal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Terminal</label>
    <referenceTo>Terminal__c</referenceTo>
    <relationshipLabel>Flight Details</relationshipLabel>
    <relationshipName>Flight_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipName>Flight_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Departure_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Departure_Terminal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Terminal</label>
    <referenceTo>Terminal__c</referenceTo>
    <relationshipLabel>Flight Details (Departure Terminal)</relationshipLabel>
    <relationshipName>Flight_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Schedule__c/Flight_Schedule__c.object-meta.xml
<CustomObject>
    <label>Flight Schedule</label>
    <nameField>
        <displayFormat>FS-{00000}</displayFormat>
        <label>Flight Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Schedule__c/fields/Arrival_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Terminal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Terminal</label>
    <referenceTo>Terminal__c</referenceTo>
    <relationshipLabel>Flight Schedules</relationshipLabel>
    <relationshipName>Flight_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Schedule__c/fields/Departure_Terminal__c.field-meta.xml
<CustomField>
    <fullName>Departure_Terminal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Terminal</label>
    <referenceTo>Terminal__c</referenceTo>
    <relationshipLabel>Flight Schedules (Departure Terminal)</relationshipLabel>
    <relationshipName>Flight_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Schedule__c/fields/Flight_Detail__c.field-meta.xml
<CustomField>
    <fullName>Flight_Detail__c</fullName>
    <label>Flight Detail</label>
    <referenceTo>Flight_Detail__c</referenceTo>
    <relationshipLabel>Flight Schedules</relationshipLabel>
    <relationshipName>Flight_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/Order_Request__c.object-meta.xml
<CustomObject>
    <description>This object will handle requested change order</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{00000}</displayFormat>
        <label>Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Request__c/fields/Arrival_Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Service_Time__c</fullName>
    <label>Arrival Service Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Order Requests</relationshipLabel>
    <relationshipName>Order_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <label>CGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Change_Type__c.field-meta.xml
<CustomField>
    <fullName>Change_Type__c</fullName>
    <label>Change Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Refund Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Date_of_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Arrival__c</fullName>
    <label>Date of Arrival</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Date_of_Departure__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Departure__c</fullName>
    <label>Date of Departure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Departure_Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Service_Time__c</fullName>
    <label>Departure Service Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Flight_Number_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number_Arrival__c</fullName>
    <label>Flight Number Arrival</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Flight_Number_Departure__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number_Departure__c</fullName>
    <label>Flight Number Departure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <label>IGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Rescheduling_Charges__c.field-meta.xml
<CustomField>
    <fullName>Rescheduling_Charges__c</fullName>
    <label>Rescheduling Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Serialized_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Data__c</fullName>
    <label>Serialized Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <label>SGST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/STA_Time__c.field-meta.xml
<CustomField>
    <fullName>STA_Time__c</fullName>
    <label>STA Time</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Refund Initiated</fullName>
            </value>
            <value>
                <fullName>Refund Approved</fullName>
            </value>
            <value>
                <fullName>Refund Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Request__c/fields/STD_Time__c.field-meta.xml
<CustomField>
    <fullName>STD_Time__c</fullName>
    <label>STD Time</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Detail</label>
    <nameField>
        <label>Passengers Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger_Details__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Airline_PNR__c.field-meta.xml
<CustomField>
    <fullName>Airline_PNR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline PNR</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Passenger_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Individual_Booking_Details__c.field-meta.xml
<CustomField>
    <fullName>Individual_Booking_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Booking Details</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Passenger Details</relationshipLabel>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Order_Request__c.field-meta.xml
<CustomField>
    <fullName>Order_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Request</label>
    <referenceTo>Order_Request__c</referenceTo>
    <relationshipLabel>Passenger Details</relationshipLabel>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_Class__c.field-meta.xml
<CustomField>
    <fullName>Travel_Class__c</fullName>
    <label>Travel Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_PNR_No__c.field-meta.xml
<CustomField>
    <fullName>Travel_PNR_No__c</fullName>
    <label>Travel PNR No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Master__mdt/State_Master__mdt.object-meta.xml
<CustomObject>
    <label>State Master</label>
    <pluralLabel>State Master</pluralLabel>
</CustomObject>

force-app/main/default/objects/State_Master__mdt/fields/State_Short_Form__c.field-meta.xml
<CustomField>
    <fullName>State_Short_Form__c</fullName>
    <label>State Short Form</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RescheduleBookingPIController.cls
public class RescheduleBookingPIController {
    @AuraEnabled
    public static void createContentVersion(String recordId, String base64Data) {
        try {
            // Decode the Base64 PDF data
            Blob pdfBlob = EncodingUtil.base64Decode(base64Data);
            
            // Create ContentVersion to upload the file
            ContentVersion contentVersion = new ContentVersion();
            contentVersion.Title = 'Generated_PDF';
            contentVersion.PathOnClient = 'Generated_PDF.pdf';
            contentVersion.VersionData = pdfBlob;
            contentVersion.IsMajorVersion = true;
            
            // Insert ContentVersion
            insert contentVersion;
            
            // Get ContentDocumentId after insert
            ContentDocument contentDocument = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId = :contentVersion.Id LIMIT 1];
            
            // Create ContentDocumentLink to link the file to the record
            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
            contentDocumentLink.ContentDocumentId = contentDocument.Id;
            contentDocumentLink.LinkedEntityId = recordId;  // Link to the record (Account, Opportunity, etc.)
            contentDocumentLink.ShareType = 'V';  // 'V' for Viewer access
            contentDocumentLink.Visibility = 'AllUsers';  // Can be 'AllUsers' or 'InternalUsers'
            
            // Insert the ContentDocumentLink to associate the file with the record
            insert contentDocumentLink;
            
            System.debug('File successfully attached to record');
        } catch (Exception e) {
            System.debug('Error while creating file: ' + e.getMessage());
            throw new AuraHandledException('Error while creating file: ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static String generateAndSavePDF(String recordId) {
        try {
            // Call VF Page with only `recordId`
            PageReference pdfPage = Page.RescheduleBookingProformaInvoice;
            pdfPage.getParameters().put('recordId', recordId);
            System.debug('DEBUG: Calling VF Page with recordId: ' + recordId);
            
            // Generate PDF Blob
            Blob pdfBlob;
            if (Test.IsRunningTest())
            {
                pdfBlob = Blob.valueOf('UNIT.TEST');
            }
            else
            {
                pdfBlob = pdfPage.getContent();
            }
            String todayDate = System.now().format();
            
            ContentVersion cv = new ContentVersion(
                Title = 'Proforma_Invoice_' + todayDate + '.pdf',
                PathOnClient = 'Proforma_Invoice_' + todayDate + '.pdf',
                VersionData = pdfBlob,
                IsMajorVersion = true
            );
            insert cv;
            
            // Attach PDF to Opportunity
            ContentDocument contentDocument = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId = :cv.Id LIMIT 1];
            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
            contentDocumentLink.ContentDocumentId = contentDocument.Id;
            contentDocumentLink.LinkedEntityId = recordId;
            contentDocumentLink.ShareType = 'V';
            contentDocumentLink.Visibility = 'AllUsers';
            insert contentDocumentLink;
            
            System.debug('PDF successfully generated and attached.');
            
            //Logic to update opportunity stage once voucher is created
            Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Id = :recordId LIMIT 1];
            if (opp.StageName == 'Quotation' || opp.StageName == null || opp.StageName == '') {                
                opp.StageName = 'Quotation Sent';            
                // Update the Opportunity record
                update opp;
            }
            
            return opp.StageName;
            
        } catch (Exception e) {
            System.debug('ERROR: Failed to generate PDF - ' + e.getMessage());
            throw new AuraHandledException('Failed to generate PDF: ' + e.getMessage());
        }
    }
    
    public Opportunity opp { get; set; }
    Public List<Order_Request__c> orderRequestList {get; set;}
    Public List<Passenger_Details__c> passengerRecords {get; set;}
    public Decimal totalAmount { get; set; }
    public Decimal paidAmount { get; set; }
    public Decimal dueAmount { get; set; }
    public Decimal totalSGST { get; set; }
    public Decimal totalCGST { get; set; }
    public Decimal totalIGST { get; set; }
    public Decimal taxableAmount { get; set; }
    public String totalAmountInWords {get; set; }
    public String formattedTodayDate { get; set; }
    public List<orderRequestWrapper> orderRequestRecords{ get; set; }
    public List<PassengerWrapper> passengers { get; set; }
    public List<FlightDetailsWrapper> flightDetails { get; set; }
    public ServiceDetailsWrapper serviceDetails { get; set; }
    public String stateCode { get; set; } 
    public Boolean hasDiscount { get; set; }
    public Boolean hide { get; set; }
    
    
    public RescheduleBookingPIController() {
        String recordId = ApexPages.currentPage().getParameters().get('recordId');
        System.debug(' DEBUG: Received recordId in VF Controller: ' + recordId);
        hasDiscount = false;
        hide = false;
        
        Date todayDate = System.today();
        formattedTodayDate = DateTime.newInstance(todayDate.year(), todayDate.month(), todayDate.day()).format('dd-MMM-yyyy');
        
        String flightNum;
        String airline;
        String terminal;
        String flightDateTime;
        String serviceDateTime;
        String fromAirport;
        String toAirport;
        
        if (String.isNotBlank(recordId)) {
            List<String> statusList = new List<String>{'Partially Cancelled','Cancellation','Fully Cancelled'};
                opp = [SELECT Id, Name, CreatedDate, Service_Type__c, Service_Airport__c, Flight_Type__c,Service_Airport_Id__r.State__c, 
                       Flight_Number_Arrival__c, Flight_Number_Departure__c,Departure_Airport__c, Arriving_Airport__c, Date_of_Arrival__c, 
                       Date_of_Departure__c, STA_Time__c, STD_Time__c, Departure_Service_Time__c, Arrival_Service_Time__c,
                       Departure_Flight_Schedule__c, Arriving_Flight_Schedule__c, Paid_Amount__c, Total_Booking_Amount__c,
                       Account.Name, Account.BillingState, Account.BillingCountry, Account.GST__c,
                       //(SELECT Id, Name, Age__c, Travel_Class__c,Travel_PNR_No__c, Airline_PNR__c FROM Passenger_Details__r),
                       (SELECT Id, CreatedDate, Product2.Name, Product2.Package_Is_For__c, Product2.Family, Quantity, UnitPrice, TotalPrice, HSN_HAC__c, 
                        Discount_Amount__c,Invoice_Amount__c,SGST__c,CGST__c,IGST__c, Opportunity_Product__c
                        FROM OpportunityLineItems WHERE Status__c NOT IN : statusList )
                       FROM Opportunity WHERE Id = :recordId];
            
            System.debug('Successfully fetched Opportunity record.');
            stateCode = getStateCode(opp.Account.BillingState);
            orderRequestList = [SELECT Id,Status__c, Change_Type__c,Serialized_Data__c,Rescheduling_Charges__c,
                                Flight_Number_Arrival__c,Date_of_Arrival__c,STA_Time__c,Date_of_Departure__c,STD_Time__c,
                                Flight_Number_Departure__c,Service_Type__c,CreatedDate
                                FROM Order_Request__c 
                                WHERE Status__c = 'Pending' AND Change_Type__c ='Reschedule' AND Booking__c =: recordId LIMIT 1];
            //Process Opportunity Line Items
            //Map<String, List<OpportunityLineItem>> productVsOppItemList = new Map<String, List<OpportunityLineItem>>();
            //Map<Id, OpportunityLineItem> oppLineItemMap = new Map<Id, OpportunityLineItem>();
            String jsonString = orderRequestList[0].Serialized_Data__c;
            Map<String, Object> dataMap = new Map<String, Object>();
            if(!Test.isRunningTest()){
               dataMap = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
            }
            
            String arrivingFlightScheduleId = '';
            String departureFlightScheduleId = '';
            
            if (dataMap.containsKey('Arriving_Flight_Schedule__c') && dataMap.get('Arriving_Flight_Schedule__c') != null) {
                arrivingFlightScheduleId = (String) dataMap.get('Arriving_Flight_Schedule__c');
            }            
            if (dataMap.containsKey('Departure_Flight_Schedule__c') && dataMap.get('Departure_Flight_Schedule__c') != null) {
                departureFlightScheduleId = (String) dataMap.get('Departure_Flight_Schedule__c');
            }
            
            Integer sr = 0;
            String serviceType;
            Decimal hsn;
            Integer totalQty;
            Decimal totalInvoice;
            Decimal totalDiscount;
            Decimal totalUnitPrice;
            Decimal valueWithTax ;
            Set<Id> orderRequestId = new Set<Id>();
            for(Order_Request__c ordReq : orderRequestList){
                orderRequestId.add(ordReq.Id);
            }
            if(!orderRequestList.IsEmpty()){
                //hide = true;
                for (OpportunityLineItem o : opp.OpportunityLineItems) 
                {
                    if(o.HSN_HAC__c != null){
                        hsn = o.HSN_HAC__c;
                    }
                    break;					
                }
                for(Order_Request__c ord:  orderRequestList){
                    sr++ ;
                    totalSGST = 0;
                    totalCGST = 0;
                    totalIGST = 0;
                    orderRequestRecords = new List<orderRequestWrapper>();
                    Decimal gstRate = 18;  // 18% GST
                    serviceType = 'Rescheduling Charges';
                    totalDiscount = 0.0;
                    valueWithTax = ord.Rescheduling_Charges__c;//opp.Total_Booking_Amount__c - ord.Rescheduling_Charges__c;
                    totalInvoice = (valueWithTax / (1 + (gstRate / 100))).setScale(2, RoundingMode.HALF_UP); 
                    totalUnitPrice = totalInvoice;
                    orderRequestRecords.add(new orderRequestWrapper(sr, serviceType, hsn, 1, totalInvoice, totalDiscount, totalUnitPrice));
                    
                    totalAmount = valueWithTax;
                    taxableAmount = totalInvoice;
                    if(opp.Service_Airport_Id__r.State__c == opp.Account.BillingState){
                        totalSGST = (totalUnitPrice - totalInvoice)/2;
                        totalCGST = (totalUnitPrice - totalInvoice)/2;
                    }else{
                        totalIGST = totalUnitPrice - totalInvoice;
                    }
                    paidAmount = opp.Paid_Amount__c != null ? opp.Paid_Amount__c : 0;
                    dueAmount = totalAmount - paidAmount;
                    totalAmountInWords = opp.Paid_Amount__c != 0 ? NumberToWordsUtil.convertNumberToWords(dueAmount) : NumberToWordsUtil.convertNumberToWords(totalAmount);
                }
                
                /*Set<Id> orderRequestIds = new Set<Id>();
for (Order_Request__c req : orderRequestList) {
orderRequestIds.add(req.Id);
}
List<Passenger_Details__c> passengerRecords = [SELECT Id, Name, Age__c,Travel_PNR_No__c,Travel_Class__c FROM Passenger_Details__c WHERE Order_Request__c IN :orderRequestIds];*/
                
                List<Passenger_Details__c> passengerRecords  = [SELECT Id, Name, Age__c, Travel_Class__c,Travel_PNR_No__c, Airline_PNR__c FROM Passenger_Details__c WHERE Opportunity_ID__c = :recordId AND Individual_Booking_Details__r.Status__c NOT IN : statusList];
                passengers = new List<PassengerWrapper>();
                Integer counter = 1;
                for (Passenger_Details__c p : passengerRecords) {
                    passengers.add(new PassengerWrapper(counter, p));
                    counter++;
                }    
                
                Map<Id, Flight_Schedule__c> flightSchMap = new Map<Id, Flight_Schedule__c>(
                    [SELECT id, Name,Flight_Detail__r.Airline_Id__c, Flight_Detail__r.Airline_Id__r.Airline_Name__c, 
                     Arrival_Terminal__r.Name, Departure_Terminal__r.Name,Flight_Detail__r.Departure_Airport__r.Name ,
                     Flight_Detail__r.Arrival_Airport__r.Name, Flight_Detail__r.Flight_Type__c
                     FROM Flight_Schedule__c 
                     WHERE Id =: arrivingFlightScheduleId OR Id =: departureFlightScheduleId]);
                
                string serviceAirport = '';
                String flightType = '';
                flightDetails = new List<FlightDetailsWrapper>();
                if(orderRequestList[0].Service_Type__c == 'Transit' || orderRequestList[0].Service_Type__c == 'Arrival'){
                    flightNum = orderRequestList[0].Flight_Number_Arrival__c;
                    flightDateTime = orderRequestList[0].Date_of_Arrival__c +' '+ orderRequestList[0].STA_Time__c;
                    airline =  flightSchMap.get(arrivingFlightScheduleId).Flight_Detail__r.Airline_Id__c != null ? flightSchMap.get(arrivingFlightScheduleId).Flight_Detail__r.Airline_Id__r.Airline_Name__c : '';
                    terminal = flightSchMap.get(arrivingFlightScheduleId).Arrival_Terminal__r.Name;
                    flightDetails.add(new FlightDetailsWrapper(flightNum, flightDateTime, airline, terminal));
                    
                    fromAirport = flightSchMap.get(arrivingFlightScheduleId).Flight_Detail__r.Departure_Airport__r.Name;
                    toAirport = flightSchMap.get(arrivingFlightScheduleId).Flight_Detail__r.Arrival_Airport__r.Name;
                    //if(orderRequestList[0].Service_Type__c == 'Transit' || orderRequestList[0].Service_Type__c == 'Arrival')
                    serviceDateTime = orderRequestList[0].Date_of_Arrival__c +' '+ orderRequestList[0].STA_Time__c;
                    serviceAirport = flightSchMap.get(arrivingFlightScheduleId).Flight_Detail__r.Arrival_Airport__r.Name ;
                    flightType = flightSchMap.get(arrivingFlightScheduleId).Flight_Detail__r.Flight_Type__c != null ? flightSchMap.get(arrivingFlightScheduleId).Flight_Detail__r.Flight_Type__c : opp.Flight_Type__c;
                }
                if(orderRequestList[0].Service_Type__c == 'Departure'){
                    flightNum = orderRequestList[0].Flight_Number_Departure__c;
                    flightDateTime = orderRequestList[0].Date_of_Departure__c +' '+ orderRequestList[0].STD_Time__c;
                    airline =  flightSchMap.get(departureFlightScheduleId).Flight_Detail__r.Airline_Id__c != null ? flightSchMap.get(departureFlightScheduleId).Flight_Detail__r.Airline_Id__r.Airline_Name__c : '';
                    terminal = flightSchMap.get(departureFlightScheduleId).Departure_Terminal__r.Name;
                    flightDetails.add(new FlightDetailsWrapper(flightNum, flightDateTime, airline, terminal));
                    
                    fromAirport = flightSchMap.get(departureFlightScheduleId).Flight_Detail__r.Departure_Airport__r.Name;
                    toAirport = flightSchMap.get(departureFlightScheduleId).Flight_Detail__r.Arrival_Airport__r.Name;
                    //if(orderRequestList[0].Service_Type__c == 'Departure')
                    serviceDateTime = orderRequestList[0].Date_of_Departure__c +' '+ orderRequestList[0].STD_Time__c;
                    serviceAirport = flightSchMap.get(departureFlightScheduleId).Flight_Detail__r.Arrival_Airport__r.Name ;
                    flightType = flightSchMap.get(departureFlightScheduleId).Flight_Detail__r.Flight_Type__c != null ? flightSchMap.get(departureFlightScheduleId).Flight_Detail__r.Flight_Type__c : opp.Flight_Type__c;
                }
                
                serviceDetails = new ServiceDetailsWrapper(serviceDateTime, String.valueof(orderRequestList[0].CreatedDate), serviceAirport, flightType, fromAirport, toAirport);
            }
        } else {
            System.debug('ERROR: No recordId found.');
        }
    }
    public static String getStateCode(String stateName){
        Map<String, Decimal> stateMap = new Map<String, Decimal>();
        for(State_Master__mdt st : [SELECT Id, Label, State_Short_Form__c, State_Code__c FROM State_Master__mdt]){
            stateMap.put(st.Label, st.State_Code__c);
            stateMap.put(st.State_Short_Form__c, st.State_Code__c);
            if(st.Label == 'Delhi')
                stateMap.put('DEL', st.State_Code__c);
            else if(st.Label == 'Hyderabad')
                stateMap.put('HYD', st.State_Code__c);
            else if(st.Label == 'Goa')
                stateMap.put('GOX', st.State_Code__c);
        }
        return String.valueOf(stateMap.get(stateName));
    }
    
    public class PassengerWrapper {
        public Integer SrNo { get; set; }
        public Passenger_Details__c Passenger { get; set; }
        
        public PassengerWrapper(Integer srNo, Passenger_Details__c passenger) {
            this.SrNo = srNo;
            this.Passenger = passenger;
        }
    }
    public class orderRequestWrapper {
        public Integer SrNo { get; set; }
        public String serviceType { get; set; }
        public Decimal hsn_hac { get; set; }
        public Integer quantity { get; set; }
        public Decimal invoiceAmt { get; set; }
        public Decimal discountAmt { get; set; }
        public Decimal unitPrice { get; set; }
        
        public orderRequestWrapper(Integer srNo, String serviceType, Decimal hsn_hac, Integer quantity, Decimal invoiceAmt, Decimal discountAmt, Decimal unitPrice) {
            this.SrNo = srNo;
            this.serviceType = serviceType;
            this.hsn_hac = hsn_hac;
            this.quantity = quantity;
            this.invoiceAmt = invoiceAmt;
            this.discountAmt = discountAmt;
            this.unitPrice = unitPrice;
        }
    }
    public class FlightDetailsWrapper{
        public String flightNo { get; set; }
        public String flightDateTime { get; set; }
        public String airline { get; set; }
        public String terminal { get; set; }
        
        public FlightDetailsWrapper(String flightNo, String flightDateTime, String airline, String terminal) {
            System.debug('--- Entered FlightDetailsWrapper---');
            this.flightNo = flightNo;
            this.flightDateTime = flightDateTime;
            this.airline = airline;
            this.terminal = terminal;
        }
    }
    
    public class ServiceDetailsWrapper{
        public String serviceDateTime { get; set; }
        public String bookingDateTime { get; set; }
        public String serviceAirport { get; set; }
        public String sectorOfTravel { get; set; }
        public String fromAirport { get; set; }
        public String toAirport { get; set; }
        
        public ServiceDetailsWrapper(String serviceDateTime, String bookingDateTime, String serviceAirport, String sectorOfTravel, String fromAirport, String toAirport) {
            this.serviceDateTime = serviceDateTime;
            this.bookingDateTime = bookingDateTime;
            this.serviceAirport = serviceAirport;
            this.sectorOfTravel = sectorOfTravel;
            this.fromAirport = fromAirport;
            this.toAirport = toAirport;
        }
        
    }
    public String getDiscountColumnStyle() {
        return hasDiscount ? '' : 'display:none;';
    }
    public Boolean getIsIntraStateTax() {
        return totalSGST > 0 || totalCGST > 0;
    }
    
    public Boolean getIsInterStateTax() {
        return totalIGST > 0;
    }   
}