force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Invoice__c/Tax_Invoice__c.object-meta.xml
<CustomObject>
    <label>Tax Invoice</label>
    <nameField>
        <displayFormat>ENC/25-26/{000000}</displayFormat>
        <label>Tax Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Invoice__c/fields/Acknowledgement_Date__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgement_Date__c</fullName>
    <label>Acknowledgement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Acknowledgement_Number__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgement_Number__c</fullName>
    <label>Acknowledgement Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/ClearTax_request_json__c.field-meta.xml
<CustomField>
    <fullName>ClearTax_request_json__c</fullName>
    <label>ClearTax request json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/ClearTax_response_json__c.field-meta.xml
<CustomField>
    <fullName>ClearTax_response_json__c</fullName>
    <label>ClearTax response json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/ClearTax_Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>ClearTax_Retry_Count__c</fullName>
    <label>ClearTax Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IRN_GENERATED</fullName>
            </value>
            <value>
                <fullName>IRN_CANCELLED</fullName>
            </value>
            <value>
                <fullName>NOT_CREATED</fullName>
            </value>
            <value>
                <fullName>DOCUMENT_VALIDATION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/EWB_Date__c.field-meta.xml
<CustomField>
    <fullName>EWB_Date__c</fullName>
    <label>EWB Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/EWB_Number__c.field-meta.xml
<CustomField>
    <fullName>EWB_Number__c</fullName>
    <label>EWB Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/EWB_Valid_Till__c.field-meta.xml
<CustomField>
    <fullName>EWB_Valid_Till__c</fullName>
    <label>EWB Valid Till</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/IRN__c.field-meta.xml
<CustomField>
    <fullName>IRN__c</fullName>
    <label>IRN</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tax Invoices</relationshipLabel>
    <relationshipName>Tax_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Oracle_request_json__c.field-meta.xml
<CustomField>
    <fullName>Oracle_request_json__c</fullName>
    <label>Oracle request json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Oracle_response_json__c.field-meta.xml
<CustomField>
    <fullName>Oracle_response_json__c</fullName>
    <label>Oracle response json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Oracle_Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Retry_Count__c</fullName>
    <label>Oracle Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Oracle_Status__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Status__c</fullName>
    <label>Oracle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Sent_to_Oracle__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Oracle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to Oracle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Signed_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Signed_Invoice__c</fullName>
    <label>Signed Invoice</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice__c/fields/Signed_QR_Code__c.field-meta.xml
<CustomField>
    <fullName>Signed_QR_Code__c</fullName>
    <label>Signed QR Code</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/Tax_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Tax Invoice Item</label>
    <nameField>
        <label>Tax Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/CGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount__c</fullName>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/GST_Rate__c.field-meta.xml
<CustomField>
    <fullName>GST_Rate__c</fullName>
    <label>GST Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/HSN_Code__c.field-meta.xml
<CustomField>
    <fullName>HSN_Code__c</fullName>
    <label>HSN Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/IGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>IGST_Amount__c</fullName>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/SGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount__c</fullName>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/Tax_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Tax_Invoice__c</fullName>
    <label>Tax Invoice</label>
    <referenceTo>Tax_Invoice__c</referenceTo>
    <relationshipLabel>Tax Invoice Items</relationshipLabel>
    <relationshipName>Tax_Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Invoice_Item__c/fields/Total_Item_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Value__c</fullName>
    <label>Total Item Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TaxInvoiceRecordHandler.cls
public class TaxInvoiceRecordHandler {
    
    public static List<OpportunityLineItem> getOpportunityLineItems(String oppId, String oppStage){
        
        List<String> cancelledStatusList = new List<String>{'Partially Cancelled','Cancellation','Fully Cancelled'};
        List<OpportunityLineItem> oppLineItemList;
        
        if(oppStage == 'Service Rendered' || oppStage == 'No Show')
        {
            oppLineItemList = [SELECT Id, OpportunityId , CreatedDate, Product2.Name, Product2.Package_Is_For__c, Product2.Family, Quantity, 
                               UnitPrice, TotalPrice, HSN_HAC__c, Discount_Amount__c,Invoice_Amount__c,Amount_Deducted__c,SGST__c,CGST__c,IGST__c, Opportunity_Product__c
                               FROM OpportunityLineItem WHERE OpportunityId  =: oppId AND Status__c NOT IN : cancelledStatusList];
        }
        else if(oppStage == 'Cancelled')
        {
            oppLineItemList = [SELECT Id, OpportunityId , CreatedDate, Product2.Name, Product2.Package_Is_For__c, Product2.Family, Quantity, 
                               UnitPrice, TotalPrice, HSN_HAC__c, Discount_Amount__c,Invoice_Amount__c,Amount_Deducted__c,SGST__c,CGST__c,IGST__c, Opportunity_Product__c
                               FROM OpportunityLineItem WHERE OpportunityId  =: oppId AND Status__c IN : cancelledStatusList];
        }
        return oppLineItemList;
    }
    
    public static Tax_Invoice__c createTaxInvoiceRecord(Opportunity opp, List<OpportunityLineItem> lineItems){
       // List<OppLineItemWrapper> oppLineItems = prepareLineItemWrapper(opp, lineItems, isCancelledInvoice);
        List<OppLineItemWrapper> oppLineItems = prepareLineItemWrapper(opp, lineItems);
        
        System.debug('oppLineItems.size()-->'+oppLineItems.size());
        return(insertTaxInvoiceRecords(opp, oppLineItems));
    }
    
    public static List<OppLineItemWrapper> prepareLineItemWrapper(Opportunity opp, List<OpportunityLineItem> lineItems){
        System.debug('--ENTERED prepareLineItemWrapper--lineItems.size()-->'+lineItems.size());
        List<OppLineItemWrapper> oppLineItems = new List<OppLineItemWrapper>();
        Map<String, List<OpportunityLineItem>> productVsOppItemList = new Map<String, List<OpportunityLineItem>>();
        Map<Id, OpportunityLineItem> oppLineItemMap = new Map<Id, OpportunityLineItem>();
        Integer sr = 0;
        String description;
        Decimal hsn;
        Integer qty;
        Decimal unitPrice;
        Decimal invAmt;
        Decimal discAmt;
        Decimal cgst;
        Decimal sgst;
        Decimal igst;
        
        if(opp.StageName == 'Service Rendered' || opp.StageName == 'No Show'){
            for (OpportunityLineItem o : lineItems) 
            {
                oppLineItemMap.put(o.Id, o);
                String productUniqueCode = o.Product2.Name == 'Surcharge' ? 'Surcharge' : o.Product2.Name +'_'+ o.Product2.Family +'_'+ o.Product2.Package_Is_For__c;
                
                System.debug('productUniqueCode-->'+productUniqueCode);
                if (!productVsOppItemList.containsKey(productUniqueCode)) {
                    System.debug('productVsOppItemList.containsKey(productUniqueCode)-->'+productVsOppItemList.containsKey(productUniqueCode));
                    productVsOppItemList.put(productUniqueCode, new List<OpportunityLineItem>{o});
                }
                else if(!productVsOppItemList.get(productUniqueCode)[0].Product2.Name.contains('Surcharge')){
                    System.debug('productVsOppItemList.get(productUniqueCode)[0].Product2.Name-->'+productVsOppItemList.get(productUniqueCode)[0].Product2.Name);
                    productVsOppItemList.get(productUniqueCode).add(o);
                }
                else if(productVsOppItemList.get(productUniqueCode)[0].Product2.Name == 'Surcharge'){
                    if(productVsOppItemList.get(productUniqueCode)[0].CreatedDate < o.CreatedDate)
                    {
                        productVsOppItemList.get(productUniqueCode).remove(0);
                        productVsOppItemList.get(productUniqueCode).add(o);
                    }
                }
                else if(productVsOppItemList.get(productUniqueCode)[0].Product2.Name == 'Surcharge Waive Off'){
                    if(productVsOppItemList.get(productUniqueCode)[0].CreatedDate < o.CreatedDate)
                    {
                        productVsOppItemList.get(productUniqueCode).remove(0);
                        productVsOppItemList.get(productUniqueCode).add(o);
                    }
                }
            }
            
            for (String key : productVsOppItemList.keySet()) 
            {
                sr++;
                qty = 0;
                invAmt = 0;
                discAmt = 0;
                unitPrice = 0;
                cgst = 0;
                sgst = 0;
                igst = 0;
                for (OpportunityLineItem oli : productVsOppItemList.get(key)) 
                {
                    qty++;
                    invAmt += oli.Invoice_Amount__c != null ? oli.Invoice_Amount__c : 0;
                    discAmt += oli.Discount_Amount__c != null ? oli.Discount_Amount__c : 0;
                    cgst += oli.CGST__c != null ? oli.CGST__c : 0;
                    sgst += oli.SGST__c != null ? oli.SGST__c : 0;
                    igst += oli.IGST__c != null ? oli.IGST__c : 0;
                    unitPrice = oli.Invoice_Amount__c != null ? oli.Invoice_Amount__c : 0;
                    hsn = oli.HSN_HAC__c;
                    description = oli.Product2.Name;
                    if (oli.Product2.Package_Is_For__c == 'Adult' || oli.Product2.Package_Is_For__c == 'Child' || oli.Product2.Package_Is_For__c == 'Infant') 
                        description = oli.Product2.Name +'-'+ oli.Product2.Package_Is_For__c;
                }
                invAmt = invAmt.setScale(2, RoundingMode.HALF_UP);
                discAmt = discAmt.setScale(2, RoundingMode.HALF_UP);
                unitPrice = unitPrice.setScale(2, RoundingMode.HALF_UP);
                oppLineItems.add(new OppLineItemWrapper(sr, description, hsn, qty, invAmt, discAmt, unitPrice, cgst, sgst, igst));
                
            }
        }
        else if(opp.StageName == 'Cancelled'){
            for (OpportunityLineItem o : lineItems) 
            {
                String productUniqueCode = o.Product2.Package_Is_For__c != null ? o.Product2.Package_Is_For__c : o.Product2.Family;
                System.debug('productUniqueCode-->'+productUniqueCode);
                if (!productVsOppItemList.containsKey(productUniqueCode)) {
                    System.debug('productVsOppItemList.containsKey(productUniqueCode)-->'+productVsOppItemList.containsKey(productUniqueCode));
                    productVsOppItemList.put(productUniqueCode, new List<OpportunityLineItem>{o});
                }
                else{
                    productVsOppItemList.get(productUniqueCode).add(o);
                }
            }
            
            Decimal  totalAmount = 0;
            for(String prdt : productVsOppItemList.keySet()){
                sr++;
                qty = 0;
                invAmt = 0;
                discAmt = 0;
                unitPrice = 0;
                cgst = 0;
                sgst = 0;
                igst = 0;
                for (OpportunityLineItem oli : productVsOppItemList.get(prdt)) 
                {
                    System.debug('oli.Amount_Deducted__c-->'+oli.Amount_Deducted__c);
                    
                    qty++;
                    invAmt += oli.Invoice_Amount__c != null ? oli.Invoice_Amount__c : 0;
                    cgst += oli.CGST__c != null ? oli.CGST__c : 0;
                    sgst += oli.SGST__c != null ? oli.SGST__c : 0;
                    igst += oli.IGST__c != null ? oli.IGST__c : 0;
                    unitPrice = oli.Invoice_Amount__c != null ? oli.Invoice_Amount__c : 0;
                    hsn = oli.HSN_HAC__c;
                    description = 'Cancellation';
                }
                // taxableAmount += totalInvoice;
                invAmt = invAmt.setScale(2, RoundingMode.HALF_UP);
                unitPrice = unitPrice.setScale(2, RoundingMode.HALF_UP);
                
                oppLineItems.add(new OppLineItemWrapper(sr, description, hsn, qty, invAmt, discAmt, unitPrice, cgst, sgst, igst));
                
            }
        }
        return oppLineItems;
    }
    
    public static Tax_Invoice__c insertTaxInvoiceRecords(Opportunity opp, List<OppLineItemWrapper> oppLineItems){
        Tax_Invoice__c taxRec = new Tax_Invoice__c();
        taxRec.Opportunity__c = opp.Id;
        taxRec.Invoice_Date__c = System.Today();
        insert taxRec;
        
        List<Tax_Invoice_Item__c> taxItemListToInsert = new List<Tax_Invoice_Item__c>();
        Tax_Invoice_Item__c taxItemRec;
        for(OppLineItemWrapper lineItem : oppLineItems){
            System.debug('lineItem.serviceType-->'+lineItem.description);
            taxItemRec = new Tax_Invoice_Item__c();
            taxItemRec.Tax_Invoice__c = taxRec.Id;
            taxItemRec.HSN_Code__c = lineItem.hsn_hac;
            taxItemRec.GST_Rate__c = 18;
            taxItemRec.Product_Description__c = lineItem.description;
            taxItemRec.Quantity__c = lineItem.quantity;
            taxItemRec.Unit_Price__c = lineItem.unitPrice;
            taxItemRec.Discount__c = lineItem.discountAmt;
            taxItemRec.CGST_Amount__c = lineItem.cgst;
            taxItemRec.SGST_Amount__c = lineItem.sgst;
            taxItemRec.IGST_Amount__c = lineItem.igst;
            taxItemRec.Invoice_Amount__c = lineItem.unitPrice * lineItem.quantity;
            taxItemRec.Total_Item_Value__c = lineItem.invoiceAmt + (lineItem.invoiceAmt * 0.18);
            
            taxItemRec.CGST_Amount__c.setScale(2, RoundingMode.HALF_UP);
            taxItemRec.SGST_Amount__c.setScale(2, RoundingMode.HALF_UP);
            taxItemRec.IGST_Amount__c.setScale(2, RoundingMode.HALF_UP);
            taxItemRec.Total_Item_Value__c.setScale(2, RoundingMode.HALF_UP);
            
            taxItemListToInsert.add(taxItemRec);
        }
        if(taxItemListToInsert.size() > 0)
            insert taxItemListToInsert;
        
        return taxRec;
    }
    
    public static Tax_Invoice__c updateClearTaxResponse(Tax_Invoice__c txRec, String req, String resp){
        System.debug('--Entered --updateTaxInvoiceRecord--response-->'+resp);
        Tax_Invoice__c tx;
        List<IRNResponseWrapper.IRNResponse> responses = IRNResponseWrapper.parse(resp);
			System.debug('responses[0]--> ' + responses[0]);
        System.debug('responses[0].govt_response--> ' + responses[0].govt_response);

        if (responses != null && !responses.isEmpty()) {
            IRNResponseWrapper.IRNResponse irnData = responses[0];
           // IRNResponseWrapper.GovtResponse govtRes = responses[0].govt_response; 
            
            System.debug('irnData-->'+irnData);
            
            tx = txRec;
            tx.Transaction_ID__c = irnData.transaction_id;
            tx.Document_Status__c = irnData.document_status;
            tx.IRN__c = irnData.govt_response.Irn;
            tx.Acknowledgement_Number__c = irnData.govt_response.AckNo;
            tx.Acknowledgement_Date__c = Date.valueOf(irnData.govt_response.AckDt);
            tx.Signed_Invoice__c = irnData.govt_response.SignedInvoice;
            tx.Signed_QR_Code__c = irnData.govt_response.SignedQRCode;
            tx.EWB_Number__c = irnData.govt_response.EwbNo; 
            tx.EWB_Date__c = irnData.govt_response.EwbDt != null ? DateTime.valueOf(irnData.govt_response.EwbDt) : null; 
            tx.EWB_Valid_Till__c = irnData.govt_response.EwbValidTill != null ? DateTime.valueOf(irnData.govt_response.EwbValidTill) : null;
            tx.ClearTax_request_json__c = req;
            tx.ClearTax_response_json__c = resp;
            tx.ClearTax_Retry_Count__c = tx.ClearTax_Retry_Count__c != null ? tx.ClearTax_Retry_Count__c+1 : 1;
            update tx;
        }
        return tx; 
    }
    
    public static void updateOracleResponse(Tax_Invoice__c txRec, String req, String resp, String status){
        Tax_Invoice__c tx = txRec;
        tx.Sent_to_Oracle__c = true;
        tx.Oracle_request_json__c = req;
        tx.Oracle_response_json__c = resp;
        tx.Oracle_Status__c = status;
        tx.Oracle_Retry_Count__c = tx.Oracle_Retry_Count__c != null ? tx.Oracle_Retry_Count__c+1 : 1;
        update tx;
    }
    
    public class OppLineItemWrapper {
        public Integer SrNo { get; set; }
        public String description { get; set; }
        public Decimal hsn_hac { get; set; }
        public Integer quantity { get; set; }
        public Decimal invoiceAmt { get; set; }
        public Decimal discountAmt { get; set; }
        public Decimal unitPrice { get; set; }
        public Decimal cgst { get; set; }
        public Decimal sgst { get; set; }
        public Decimal igst { get; set; }
        
        public OppLineItemWrapper(Integer srNo, String description, Decimal hsn_hac, Integer quantity, Decimal invoiceAmt, Decimal discountAmt, Decimal unitPrice, Decimal cgst, Decimal sgst, Decimal igst) {
            this.SrNo = srNo;
            this.description = description;
            this.hsn_hac = hsn_hac;
            this.quantity = quantity;
            this.invoiceAmt = invoiceAmt;
            this.discountAmt = discountAmt;
            this.unitPrice = unitPrice;
            this.cgst = cgst;
            this.sgst = sgst;
            this.igst = igst;
        }
    }
    
}