force-app/main/default/objects/Airline__c/Airline__c.object-meta.xml
<CustomObject>
    <label>Airline</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Airline Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airline__c/fields/Airline_Code__c.field-meta.xml
<CustomField>
    <fullName>Airline_Code__c</fullName>
    <label>Airline Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airline__c/fields/Airline_Name__c.field-meta.xml
<CustomField>
    <fullName>Airline_Name__c</fullName>
    <label>Airline Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arriving_Airport__mdt/Arriving_Airport__mdt.object-meta.xml
<CustomObject>
    <label>Arriving Airport</label>
    <pluralLabel>Arriving Airports</pluralLabel>
</CustomObject>

force-app/main/default/objects/Flight_Detail__c/Flight_Detail__c.object-meta.xml
<CustomObject>
    <label>Flight Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Flight Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Detail__c/fields/Airline_Id__c.field-meta.xml
<CustomField>
    <fullName>Airline_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Id</label>
    <referenceTo>Airline__c</referenceTo>
    <relationshipLabel>Flight Details</relationshipLabel>
    <relationshipName>Flight_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Flight_No_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Flight_No_Arrival__c</fullName>
    <label>Flight No Arrival</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Flight_No_Departure__c.field-meta.xml
<CustomField>
    <fullName>Flight_No_Departure__c</fullName>
    <label>Flight No Departure</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Terminal__c/Terminal__c.object-meta.xml
<CustomObject>
    <label>Terminal</label>
    <nameField>
        <label>Terminal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terminals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terminal__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terminal 1</fullName>
            </value>
            <value>
                <fullName>Terminal 2</fullName>
            </value>
            <value>
                <fullName>Terminal 3</fullName>
            </value>
            <value>
                <fullName>Terminal 4</fullName>
            </value>
            <value>
                <fullName>Terminal 5</fullName>
            </value>
            <value>
                <fullName>Terminal 3I</fullName>
            </value>
            <value>
                <fullName>Terminal 3D</fullName>
            </value>
            <value>
                <fullName>Terminal 2D</fullName>
            </value>
            <value>
                <fullName>Terminal 1D</fullName>
            </value>
            <value>
                <fullName>Terminal 1I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Flight_Booking_encalmTest.cls
/**
* @File Name : Flight_Booking_encalmTest.cls
* @Description : Enhanced Test Class for Flight_Booking_encalm.cls
* @Author : Maxify Development Team
* @Created Date : April 10, 2025
**/
@isTest
public class Flight_Booking_encalmTest {
    
    @isTest
    public static void testFlightBookingMethods() {
        // Create Test Data
        Terminal__c terminal = new Terminal__c(Name='T1', Code__c='Terminal 1I');
        insert terminal;

        Airline__c airline = new Airline__c(Airline_Name__c='Air India', Airline_Code__c='001');
        insert airline;

        Flight_Detail__c flightDetail = new Flight_Detail__c(
            Airline_Id__c = airline.Id,
            Flight_No_Arrival__c = '871',
            Flight_No_Departure__c = '0'
        );
        insert flightDetail;

        Account parentAcc = new Account(Name = 'Parent Account', BillingState = 'Delhi');
        insert parentAcc;

        Account childAcc = new Account(Name = 'Child Account', ParentId = parentAcc.Id, BillingState = 'Goa');
        insert childAcc;

        Contact con = new Contact(FirstName='Test', LastName='User', Email='test@example.com', AccountId=childAcc.Id);
        insert con;

        Test.startTest();
            List<Arriving_Airport__mdt> airportList = Flight_Booking_encalm.getAirport();
            List<Flight_Detail__c> flightList = Flight_Booking_encalm.getFlightInfo(System.today());
            Boolean result = Flight_Booking_encalm.createOpportunity('Delhi', 'Goa', System.today(), 'sector', 'FXN00', '1', '1', '2');

            List<Map<String, String>> locations = Flight_Booking_encalm.getLocation(parentAcc.Id);
            Boolean isBusiness = false;

            // Assign RecordType before calling isBusinessAccount
            RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Business_Account' LIMIT 1];
            parentAcc.RecordTypeId = rt.Id;
            update parentAcc;
            isBusiness = Flight_Booking_encalm.isBusinessAccount(parentAcc.Id);
            List<Contact> contacts = Flight_Booking_encalm.getContactsByAccount(childAcc.Id);
        
        	childAcc.ParentId = null;
            update childAcc;
        	Flight_Booking_encalm.getLocation(parentAcc.Id);
        Test.stopTest();

        // Assertions
        System.assertNotEquals(null, airportList, 'Airport list should not be null');
        System.assertNotEquals(null, flightList, 'Flight list should not be null');
        System.assertEquals(true, result, 'Opportunity creation should return true');
        System.assertEquals(1, locations.size(), 'One location should be returned');
        System.assertEquals(true, isBusiness, 'Account should be recognized as Business Account');
        System.assertEquals(1, contacts.size(), 'One contact should be returned');
    }
}