force-app/main/default/objects/Airline__c/Airline__c.object-meta.xml
<CustomObject>
    <label>Airline</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Airline Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airline__c/fields/Airline_Code__c.field-meta.xml
<CustomField>
    <fullName>Airline_Code__c</fullName>
    <label>Airline Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airline__c/fields/Airline_Name__c.field-meta.xml
<CustomField>
    <fullName>Airline_Name__c</fullName>
    <label>Airline Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Airport Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Airport_Code__c</fullName>
    <label>Airport Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/Flight_Detail__c.object-meta.xml
<CustomObject>
    <label>Flight Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Flight Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Detail__c/fields/Airline_Id__c.field-meta.xml
<CustomField>
    <fullName>Airline_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Id</label>
    <referenceTo>Airline__c</referenceTo>
    <relationshipLabel>Flight Details</relationshipLabel>
    <relationshipName>Flight_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Arrival_Airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipName>Flight_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipName>Flight_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight_Detail__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight_Schedule__c/Flight_Schedule__c.object-meta.xml
<CustomObject>
    <label>Flight Schedule</label>
    <nameField>
        <displayFormat>FS-{00000}</displayFormat>
        <label>Flight Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Schedule__c/fields/Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date__c</fullName>
    <label>Flight Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight_Schedule__c/fields/Flight_Detail__c.field-meta.xml
<CustomField>
    <fullName>Flight_Detail__c</fullName>
    <label>Flight Detail</label>
    <referenceTo>Flight_Detail__c</referenceTo>
    <relationshipLabel>Flight Schedules</relationshipLabel>
    <relationshipName>Flight_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/Passenger_Details__c.object-meta.xml
<CustomObject>
    <label>Passenger Detail</label>
    <nameField>
        <label>Passengers Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger_Details__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Passenger_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_Class__c.field-meta.xml
<CustomField>
    <fullName>Travel_Class__c</fullName>
    <label>Travel Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Premium Economy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger_Details__c/fields/Travel_PNR_No__c.field-meta.xml
<CustomField>
    <fullName>Travel_PNR_No__c</fullName>
    <label>Travel PNR No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDEN_PdfAttachmentControllerTest.cls
@IsTest
public  class MDEN_PdfAttachmentControllerTest {
    @testSetup
    static void setupTestData() {
        // Create an Account
        Account acc = new Account(
            Name = 'Test Account',
            BillingStreet = '123 Test Street',
            BillingCity = 'Test City',
            BillingState = 'Test State',
            BillingPostalCode = '12345',
            BillingCountry = 'Test Country'
        );
        insert acc;
        
        // Create an Opportunity
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = System.today().addDays(10),
            AccountId = acc.Id
        );
        insert opp;
        
        // Create OpportunityLineItems
        Product2 product = new Product2(Name = 'Test Product', IsActive = true);
        insert product;
        /*Pricebook2 customPricebook = new Pricebook2(
            Name = 'Custom Price Book',
            IsActive = true
        );
        insert customPricebook;*/
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = product.Id, UnitPrice = 100, IsActive = true);
        insert pbe;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = 100
        );
        insert oli;
        
        Passenger_Details__c pd = new Passenger_Details__c(
            Opportunity_ID__c = opp.Id, 
             Name = 'test passenger', 
             Age__c = 33, 
             Travel_Class__c ='Business',
             Travel_PNR_No__c = 'test pnr'
            );
        insert pd;
        
        Airline__c airline = new Airline__c(
            Airline_Code__c = '6E', 
            Airline_Name__c = 'Indigo Airlines'
        );
        insert airline;
        
        Airport__c airport1 = new Airport__c(
        	Airport_Code__c = 'DEL'
            );
        insert airport1;
        
        Airport__c airport2 = new Airport__c(
        	Airport_Code__c = 'HYD'
            );
        insert airport2;
        
        Flight_Detail__c fd = new Flight_Detail__c(
            Airline_Id__c = airline.Id,
            Arrival_Airport__c = airport1.id,
            Departure_Airport__c = airport2.id,
            Flight_Number__c = '123'
        );
        insert fd;
        
        Flight_Schedule__c fsch1 = new Flight_Schedule__c(
            Flight_Detail__c = fd.Id,
            Flight_Date__c = System.today()
        );
        insert fsch1;
        
        Flight_Schedule__c fsch2 = new Flight_Schedule__c(
            Flight_Detail__c = fd.Id,
            Flight_Date__c = System.today() + 1
        );
        insert fsch2;
        
        opp.Arriving_Flight_Schedule__c = fsch1.id;
        opp.Departure_Flight_Schedule__c = fsch2.id;
        opp.Service_Type__c = 'Transit';
        update opp;
        
    }
    
    @isTest
    static void testCreateContentVersion() {
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        String base64Data = EncodingUtil.base64Encode(Blob.valueOf('Test PDF Data'));
        
        Test.startTest();
        MDEN_PdfAttachmentController.createContentVersion(testOpp.Id, base64Data);
        Test.stopTest();
        
        ContentVersion cv = [SELECT Id FROM ContentVersion WHERE Title = 'Generated_PDF' LIMIT 1];
        System.assertNotEquals(null, cv, 'ContentVersion should be created.');
    }
    
    @isTest
    static void testGenerateAndSavePDF() {
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        
        Test.startTest();
        String contentVersionId = MDEN_PdfAttachmentController.generateAndSavePDF(testOpp.Id);
        Test.stopTest();
        //Added by Abhishek on 09-04-2025
        Opportunity updatedOpp = [SELECT Id, StageName FROM Opportunity WHERE Id = :testOpp.Id];
        System.assertEquals('Prospecting', updatedOpp.StageName, 'StageName should be updated to Quotation Sent');
        String todayDate = System.now().format();
		string Title = 'Proforma_Invoice_' + todayDate + '.pdf';
        List<ContentVersion> versions = [SELECT Id, Title FROM ContentVersion WHERE Title =: Title];
        System.assertEquals(1, versions.size(), 'A ContentVersion should be created');
    }
    
    @isTest
    static void testVFControllerConstructor() {
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        ApexPages.currentPage().getParameters().put('recordId', testOpp.Id);
        MDEN_PdfAttachmentController controller = new MDEN_PdfAttachmentController();
        Test.stopTest();
        
        System.assertNotEquals(null, controller.opp, 'Opportunity should be initialized.');
        System.assertNotEquals(null, controller.formattedTodayDate, 'Formatted date should be initialized.');
    }
}