force-app/main/default/objects/Timestamp__c/Timestamp__c.object-meta.xml
<CustomObject>
    <label>Timestamp</label>
    <nameField>
        <label>Timestamp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timestamps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timestamp__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timestamps</relationshipLabel>
    <relationshipName>Timestamps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TimestampChangeController.cls
/**
* @File Name : TimestampChangeController .cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : March 26, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | March 26, 2025 |   | Initial Version
**/

public class TimestampChangeController  {
	@AuraEnabled(cacheable=true)
    public static List<Timestamp__c> getStatusChanges(Id caseId) {
        return [
            SELECT Id, Status__c, Change_Timestamp__c
            FROM Timestamp__c
            WHERE Case__c = :caseId
            ORDER BY Change_Timestamp__c DESC
        ];
    }
}