force-app/main/default/objects/Payment_transaction__c/Payment_transaction__c.object-meta.xml
<CustomObject>
    <label>Payment transaction</label>
    <nameField>
        <label>Payment transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>payment transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_transaction__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>payment transactions</relationshipLabel>
    <relationshipName>payment_transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_transaction__c/fields/order_status__c.field-meta.xml
<CustomField>
    <fullName>order_status__c</fullName>
    <label>Order Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentTransactionHandler.cls
public with sharing class PaymentTransactionHandler {
    public static void handlePaymentTransaction(List<Payment_Transaction__c> paymentTransactions) {
        Set<Id> opportunityIds = new Set<Id>();

        // Collect all Opportunity Ids linked via Payment_Transaction__c
        for (Payment_Transaction__c payment : paymentTransactions) {
            if (payment.Booking__c != null && payment.order_status__c == 'Success') {
                opportunityIds.add(payment.Booking__c);
            }
        }

        if (opportunityIds.isEmpty()) {
            return;
        } else {
            OrderRequestController.updateDataFromOrderRequest(opportunityIds);
        }
		
        
    }
}